apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ${APP}
  name: ${APP}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${APP}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ${APP}
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: ${APP}
          image: ghcr.io/donkie/spoolman:latest
          env:
            - name: TZ
              value: America/Chicago
            - name: SPOOLMAN_DB_TYPE
              value: postgres
            - name: SPOOLMAN_PORT
              value: "7912"
            - name: SPOOLMAN_DB_HOST
              value: ${PGSQL_HOST}
            - name: SPOOLMAN_DB_PORT
              value: "5432"
            - name: SPOOLMAN_DB_NAME
              value: spoolman
            - name: SPOOLMAN_DB_USERNAME
              value: spoolman
            - name: SPOOLMAN_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: spoolman-postgres-secret
                  key: password
          ports:
            - containerPort: 7912
              protocol: TCP
              name: http
          volumeMounts:
            - mountPath: /home/app/.local/share/spoolman
              name: spoolman
      restartPolicy: Always
      volumes:
        - name: ${APP}
          persistentVolumeClaim:
            claimName: ${APP}
