kind: Secret
apiVersion: v1
metadata:
    name: spoolman-db-secret
type: Opaque
stringData:
    db-username: ENC[AES256_GCM,data:ksL/i6Nldh8=,iv:jf+KRKncR2hnVpmwNlYuTu1ELbnmFyovttMyLaE1p/Q=,tag:m131gTe/g6ZI3qj617+D9g==,type:str]
    db-password: ENC[AES256_GCM,data:xI8hTfq9HbW3sctAD46L5flwh3NXky8Y,iv:zrvYxWJZaMtTgpZVX3ygV0zZbkb0lv3xQnBM0quf0jc=,tag:SoQdntuI2hPHFAiTd7p9NA==,type:str]
    db-init-sql: ENC[AES256_GCM,data:UbHE/wQk5VnOkF0HqbTDxr6WiJdldWcWrtwvgeGWx8Fng89SKfzkmelo6uANljB2neKYtJIpMuj6TroN6r6BwvkcRVUCOmi3+nBxsMSJ7M1cvFQyRe0Q6tgGMRM+Fhvil1vW5jlMrbdRagJEWoc2y2TavONwytBAIzsrmJgFXTMRpsPdTW63qwg2IVYMu9HFCFLChihV1R39HoxcOq6gE+f02w6dDx3yqQ==,iv:H4TIr2pEH89St6ZGFB8IdT3z/k0LgPKp1tjiP2EwCU0=,tag:9esb/YkQy0wqN2KLs05GfQ==,type:str]
sops:
    age:
        - recipient: age13ttsf4ee2xr4e90ydsrj9hk2gpjk9hktmxam0r08zeny75dwlc7qxap6zk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKcFF4cE5NdFZhNkVTTjB2
            K0YrSnRrN0lqS1ZSbXd1emRTek1mamxaRDNzClJkZjhTSkw4Y1hXaDAzVHJQTnR4
            T0U2a3lvbTBxTmErdWtxRWdoRFMyY0kKLS0tIEt0UHp4K2JCd0pjSWNYVC9vaXVZ
            RTdkQlpZQVA2WWNsTWZmSjhJY1dLRVEKS0StUVcCLoB3N25is4PHTQQ5EZD9V69i
            zi5k3x5MeVeosnRXhpJls7YxJVO66Tx1/oN0PgZhpGFxbwxuX8aBxQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-30T19:30:43Z"
    mac: ENC[AES256_GCM,data:GUko2v2hOWCrFCaDpEDw+8XCmi6Ha4r1H6vYrelVjAxD9NLb0rTDg2k/lsfcsN2A6YNY8HIJO45xiXqj1pNJPb662KZxRP6Ccutag6hcA8mAtX097QCIpNAXZhJoXn0aeuBh7MjdVAAoKlZ4hmwoCvHjC6KhbLb4x9vXNy6ZQEY=,iv:4usLTNF3SvK+Pap4pzE6J5c+8CyGL8n8/hCDZDtdxyI=,tag:ZdeGJgF5ba+pCcxqNx/obg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
