kind: Secret
apiVersion: v1
metadata:
  name: spoolman-postgres-secret
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:8sH8PgdCtfFU12zwA2fblfs0wJvBxiLq,iv:wd/44c5zeAq7kUGQRjLLKGrVQxyxQEBqkJ4ZLzHCCjU=,tag:X2ctEFrs/IZNm+mnqrg4yw==,type:str]
sops:
  age:
    - recipient: age13ttsf4ee2xr4e90ydsrj9hk2gpjk9hktmxam0r08zeny75dwlc7qxap6zk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKcFF4cE5NdFZhNkVTTjB2
        K0YrSnRrN0lqS1ZSbXd1emRTek1mamxaRDNzClJkZjhTSkw4Y1hXaDAzVHJQTnR4
        T0U2a3lvbTBxTmErdWtxRWdoRFMyY0kKLS0tIEt0UHp4K2JCd0pjSWNYVC9vaXVZ
        RTdkQlpZQVA2WWNsTWZmSjhJY1dLRVEKS0StUVcCLoB3N25is4PHTQQ5EZD9V69i
        zi5k3x5MeVeosnRXhpJls7YxJVO66Tx1/oN0PgZhpGFxbwxuX8aBxQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-07T00:48:42Z"
  mac: ENC[AES256_GCM,data:TwPORH70fAluXA5hVbrBpGPzuOwHqoDhN3+3m7eiBQypb4wJE/pwQXePdMs/XW51+bzpch/WCVsjo+Ja1GLY+qY+pLLde+lbjJbWaLHEBRaiM1siBmPzV5iBNrdyZ0AzXRUhAnmSdExxrMfKUi5b0cB3YDW0NSV21kJlTlIOytY=,iv:rF7QbgSMP/OjrlCSgfOALuyQVxgrBfUH76sqneYjWFw=,tag:c0qrdAwvCorgXsJM7ZACdQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
