---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: stackgres-admin-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword

  target:
    name: stackgres-admin-secret

  data:
    - secretKey: username
      remoteRef:
        key: stackgres-admin-secret/username
    - secretKey: password
      remoteRef:
        key: stackgres-admin-secret/password
