apiVersion: v1
kind: Secret
metadata:
    name: dtrack-secrets
stringData:
    db-username: ENC[AES256_GCM,data:gyXbeAZ6,iv:mSOE2FqEhrmgx5+hUiErn4DpPq60gSL6mpCR8CJkI8s=,tag:MS9RZ20CuZN/W5i4pXKKUw==,type:str]
    db-password: ENC[AES256_GCM,data:66LGrOg0yzdlUW0xmdKUZcLksvFzejFcQ0XFzHF/aUk=,iv:iASf5uyLR5fc7fv79cHmchQDdWREQUzhGs+hBE2DxFk=,tag:xOFKI0d0bb3sIkWyyk6h+g==,type:str]
    db-init-sql: ENC[AES256_GCM,data:9LO63kPL+2gqlUzeOpuOJyK9QDAH+jAPeZSWF5kdV2LsHAXdAjrFhqacM/nYciXLvyaXgSUoHDEOfBQL8xqL7rrwW7F/OKvQsNZuPvxqQpNs3qcecvyJB1edu97875UsqbQgJaNr0cGvRx1jP0zkwahTlWJ2xKFsepQLUFiCFcIFRH36JxS6BCYzNHfBaRNCLMzCT/KDkToUEgrSu2hOFcHmcRosTgw=,iv:nCOVTW/w3EWKSwcZ/Iby9EpiOBXViZBR5PbzoyS4Vew=,tag:KJl1sLt5H9c6Y1Xti3b1RQ==,type:str]
sops:
    age:
        - recipient: age13ttsf4ee2xr4e90ydsrj9hk2gpjk9hktmxam0r08zeny75dwlc7qxap6zk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5dE0xNlVLV3JHN0tIRmdo
            M2JFeEd0RkZLUmtzRXJuUmhsOXpZTzA2RGhFCktSaTl1eDVjajBJcjJtQUxJdzkw
            T2IxMmU2a3N6RG9OeWFtd2Zva1B6VzgKLS0tIFNwOFlCZ01FbTl0cXFCTGFGcTF6
            c2pEeWpQakp2RzhRajhqVDFDUWRVSDQKN2ILFpT6uXxodggBtyXWyRxqSNQCIzgG
            Dnx4TIQa0FmKbVAetD0UgfraLU6sfbywlZgU5/QU/1noVpVhIc3ZJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T19:26:00Z"
    mac: ENC[AES256_GCM,data:3MJE4eetmdpAvPAO+g9harne4z1g/ontLyKMN6oiWYC+CVvbHJ4OvDrauMcZw7klK3LgpAD5XUL4RhxFIXmYuIg8x/od4BW7A4sxE4NvGbE5xXZ/R8GKyt97hcIy112p80olRRBPKrx/jNnuRujs8hhH8lS7cBe1TjqvswMzMkA=,iv:VBgoJlYZQVpUh0OHBsIRzPmw1JGLqefZZ/dfD4fW4EU=,tag:oMr4vGDRd8ZvnsIhcgs1yg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.1
