[tools]
# Repository Management
pkl = "0.32.1"
hk = "2.0.0"
prettier = "3.9.6"
ruff = "0.16.1"
shellcheck = "0.11"
yamllint = "1.38.0"
typos = "1.48.0"
task = "3.52.0"

# Scripting
python = "3.14"
jq = "1.8"
yq = "4.53.3"
cue = "0.17.1"

# Template Rendering
pipx = "1.16.5"
'pipx:makejinja' = "2.8.2"

# Encryption Tools
sops = "3.13.3"
age = "1.3.1"

# Talos Management
talos = "1.13.7"
talhelper = "3.1.15"
"aqua:cli/cli" = "2.97.0"

# Kubernetes Tools
k9s = "0.51.0"
kubectl = "latest"
kustomize = "5.8"
kubeconform = "0.8.0"
helm = "4.2.3"
helmfile = "1.7.2"
cilium-cli = "0.19.7"
flux2 = "2.9.3"

# Cloudflare Tools
cloudflared = "2026.7.3"

[env]
_.python.venv = { path = "{{config_root}}/.venv", create = true }
SOPS_AGE_KEY_FILE = "{{ config_root }}/age.key"
TEMPLATE_DIR = "{{ config_root }}/.mise/templates"
MAKEJINJA_SETTINGS = "{{ config_root }}/makejinja.toml"
BOOTSTRAP_DIR = "{{ config_root }}/bootstrap"
KUBERNETES_DIR = "{{ config_root }}/kubernetes"
SCRIPTS_DIR = "{{ config_root }}/scripts"
TALOS_DIR = "{{ config_root }}/talos"
PRIVATE_DIR = "{{ config_root }}/.private"
TALOSCONFIG = "{{ config_root }}/talos/clusterconfig/talosconfig"
KUBECONFIG = "{{ config_root }}/kubeconfig"

[tasks.reconcile]
description = "Reconcile configuration changes to the cluster"
run = [
    "flux --namespace flux-system reconcile kustomization flux-system --with-source"
]
