apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: seerr-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword

  target:
    name: seerr-secret

  data:
    - secretKey: API_KEY
      remoteRef:
        key: seerr-secret/API_KEY
