---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seerr
  namespace: media
  labels:
    homelab/backup: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ceph-block