---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seerr
  labels:
    homelab/backup: "true"
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ceph-block