apiVersion: v1
kind: Secret
metadata:
    name: seerr-secret
stringData:
    API_KEY: ENC[AES256_GCM,data:nBmhvYDf4/Uzj8TaMJD9nfIMa1omjgv5,iv:eUhCYtKLLPU/KJ2ZywRwAx4F08/6Q5j+OK+PvzNje/4=,tag:3a8lS1Do2UQjrMcARPV5xw==,type:str]
sops:
    age:
        - recipient: age13ttsf4ee2xr4e90ydsrj9hk2gpjk9hktmxam0r08zeny75dwlc7qxap6zk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3YnlCc24wRndNRWp2cFBJ
            VVZ6V0JhVisxT2NZUHpTNzMzbVRVQjM0dVVRCnZGZmdYZHlEUzg0K1ROTGNqQ21k
            emVXd056RU1rOFBIWUdaWnRMN1Q3eHMKLS0tIFFwT29iT1lZS0ZMRUZFcjRNZHRh
            ZkExNlB0dXY2MGN5ZE1WbHlhY285UVkKKf/SWWlIyCYW+4N7vUvZTmMUY5TuL7tj
            bzyN3V/sdfN97nZrGICDQN0kGreaF1PL/9lZm2MNXuY1Xfef0cwruQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-09T22:09:08Z"
    mac: ENC[AES256_GCM,data:NHfKX/+pn91RobzhdjLWhwpCALVNoH/K0QcmCnJkSBXo3u8t7fD4OS4p/DR+2elwnTrCdQAQeTZFKiWfY/IpshKmnWjMwAyKO6pJlZ0lCs58OPmE9D7ef8JEF3E/jhiDayMQLCvY9piMwPRprvKyHlk6BiQpebQMOBITY9clVUY=,iv:FbBplnJckAdE7uJmD1wl43dSeTpzzbMVsqyjgzswx9o=,tag:MV1raNlmHD4H1jlFdHxicQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
