apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword

  target:
    name: renovate-secrets

  data:
    - secretKey: RENOVATE_GITHUB_COM_TOKEN
      remoteRef:
        key: renovate-secrets/RENOVATE_GITHUB_COM_TOKEN
    - secretKey: RENOVATE_TOKEN
      remoteRef:
        key: renovate-secrets/RENOVATE_TOKEN
