apiVersion: v1
kind: Secret
metadata:
    name: renovate-secrets
stringData:
    RENOVATE_GITHUB_COM_TOKEN: ENC[AES256_GCM,data:K7tVhbj7bbQ+VKTSofwI77gk2s1DnWx/vf71DrPRbIYBVGcx5f/3cA==,iv:sIBZO5YVv1NU6bZ2t9+jOPe6aJjW8CVyRlvnaeDVdtU=,tag:CylJpRsD664cqpwRb4xA1Q==,type:str]
    RENOVATE_TOKEN: ENC[AES256_GCM,data:oYNJdIZ4/70fVoC82Fp37b2opD+UDKoevwVxIF7pcCKf1RAdXZ1C2wu3k7q+O8Vr2hN/chJjVWSozF8NW8liAwXdZ+f07mMSu7mONYK9WRuBgoG/1ET6c9PoJIbD,iv:k1EZZS37sZR5kvtMsbijtgrr5MGlR3snqmiZGRmWUl8=,tag:VQGjdgLnihimxol7UTHhUQ==,type:str]
sops:
    age:
        - recipient: age13ttsf4ee2xr4e90ydsrj9hk2gpjk9hktmxam0r08zeny75dwlc7qxap6zk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVOU1ERVBvUjRyTnRhYXZh
            dEQ0cEZjeU1mOCtUaldnRWRibDJ5MGVKREFFCkV4U3NYR2s0eDN6T1RZS0Z0M0hz
            TUFsTTVYcFA2c1VkY0ZtUEVUN3cyTUkKLS0tIFluMG9NZjJwS1RFcUZUWlZVcGF5
            Wjl4dkFWQnV6cGVac0oyT2lYK0pFME0Ka/8Qg/hw6FhUPg/horqu9P5o9dxcnM5m
            IyZ8VPBWljWotZm9EPA6q9bZTO3G7933aogwYz3C1C5G7rk/DywG+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-27T05:20:36Z"
    mac: ENC[AES256_GCM,data:hl2JGmmf+N3RmmKcQSQfajK3Jtg9uOWHzioyevlYK7cKaNDDX31zITWOPvpASj+BrdySXjloPtFyleG6tvWxR9AhRLprX54vQeBap8iv/LuBo7z+mzc0KgJ/JUseqZS+x8GMslW3/3P70hSWVqXyMULTPWWbosvsZ1JhEx/Ean8=,iv:Ne22QYGeobCZSJ5hO6e0Er6V+nEHl4mtQM8i8UXYVbM=,tag:3zozkLvcjWoXpIu/1kGilA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
