apiVersion: v1
kind: Secret
metadata:
  name: renovate-secrets
stringData:
  RENOVATE_TOKEN: ENC[AES256_GCM,data:oYNJdIZ4/70fVoC82Fp37b2opD+UDKoevwVxIF7pcCKf1RAdXZ1C2wu3k7q+O8Vr2hN/chJjVWSozF8NW8liAwXdZ+f07mMSu7mONYK9WRuBgoG/1ET6c9PoJIbD,iv:k1EZZS37sZR5kvtMsbijtgrr5MGlR3snqmiZGRmWUl8=,tag:VQGjdgLnihimxol7UTHhUQ==,type:str]
sops:
  age:
    - recipient: age13ttsf4ee2xr4e90ydsrj9hk2gpjk9hktmxam0r08zeny75dwlc7qxap6zk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVOU1ERVBvUjRyTnRhYXZh
        dEQ0cEZjeU1mOCtUaldnRWRibDJ5MGVKREFFCkV4U3NYR2s0eDN6T1RZS0Z0M0hz
        TUFsTTVYcFA2c1VkY0ZtUEVUN3cyTUkKLS0tIFluMG9NZjJwS1RFcUZUWlZVcGF5
        Wjl4dkFWQnV6cGVac0oyT2lYK0pFME0Ka/8Qg/hw6FhUPg/horqu9P5o9dxcnM5m
        IyZ8VPBWljWotZm9EPA6q9bZTO3G7933aogwYz3C1C5G7rk/DywG+g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-07T18:57:30Z"
  mac: ENC[AES256_GCM,data:9QN6vOgmseUTCq7ZgW9zXPrdFpMlpZYJw1nmjuMWFudaFE4Ie1cT8gzK6awkKOPmMp/mVb6e6tTSjzeDgNF+TsDjU6m33yqfIpsHvwQ2N9Y5el7G+VNlK2Aw43UWqX80rFYzLQMsCHm9E4GbRgbzH25l+D7+/3hvR85qRpnGU/w=,iv:G2D48WLAS+FmFG6NPhjnBZVaY2OyMon+vDyY7JtMFmA=,tag:y2oynEwlIgUFkjlMMrva0g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
