---
apiVersion: stackgres.io/v1
kind: SGCluster
metadata:
  name: default-pgsql
  namespace: database
spec:
  postgres:
    version: 'latest'
    extensions:
      - name: 'vchord'
  instances: 1
  pods:
    persistentVolume: 
      size: '25Gi'
  configurations:
    observability:
      prometheusAutobind: true
