apiVersion: v1
kind: Secret
metadata:
  name: printstash-db-secret
type: Opaque
stringData:
  db-username: ENC[AES256_GCM,data:aQFij6gd/ZMWdQ==,iv:BdTEa+01aNJb7vOPuYfgeut8Ruix1Ce4vmcLiK05Yvw=,tag:z0Ql9HCymkabjMV92SNFyg==,type:str]
  db-password: ENC[AES256_GCM,data:58Jmp+pNLVmTXM+4BJgpRCFjmwqQr2i0wQDIez0+0xv6KJIT3iuCz5/AaY1LH+ww,iv:RpFawZf5KgOY3N9tj06SzgsHeh0pyS9wstY9r+yJ/WE=,tag:0B/pxmpdULwPPbg+Q8IdJw==,type:str]
  db-url: ENC[AES256_GCM,data:s9ltvkCvnwhgbWdBVd7MNnbvJEK4lmjDlDUnXWO4rBeexpBeKmSU0AqNLJ/DzMZVK8OWp7k9G+V7I4X1TId6ILncixudxKH906O62s0hQK/Gqj33t48hsiMmH/dBq0cE/vFXpzqv1iwotu8/sPz9jluvSU8AFduwGgpQzqu0,iv:n3yF7XcjmGSf9rieixsGmcTZwuV1uYcp2+F2l3ldrls=,tag:Ql/u0Y7dDv3JA1849sXdmQ==,type:str]
  db-init-sql: ENC[AES256_GCM,data:2otpsvN3uKG07lA+tHRsMb+npH38E/My2bfJhYDOE50us6DM1KSJoI6laHnjZIBgjC6MBlpTNnTIkk9BjVYRqbmbd6qysNlM5qflXSB9IlMI33IaFin/XRKRqn2+QGK99XluI2gOK9EN8jqhZ1cyH3VkCJVfoDvSCriVq2371znt84Mf3qb8fr/zASWxneTZ1oVzo9Smd7mL/r3XzQ4jP2Lzw4nNmSwAOBXfUe+evN+9T14iCXiXz9FJefsRKeQhE+C5r0Y8m3zJ5M4=,iv:jMs/2ffOeSsCPawIM9IXCKybgPlkspOfox38vG3j32I=,tag:Syzl0WNZUJppW8NYx0+ckA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHWEJ5YXZQcXNab1lnVzJt
        NG5aOVJMU21rZDVCTkYyQTJjM2w3TG9semx3CjJSR1hwc1d2bnFjQ0QwMi9oa2FH
        R0YwYnorQlJUcGNqbHRyNXRSV3N4WUUKLS0tIGx4ZDdDVjhHVXRqL1Iva3drRkZF
        cWJYSm5sUWhBaFJTZ3VsY3YwRUJsNG8KCZa/FPUH6o3JTlahbYRU1z1WsTVQ+fdZ
        Lz2xepMmy2M6Zt4qY/7R/miMHo/VZOtSMRzk2ovqKG2cOxV/U24pWA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age13ttsf4ee2xr4e90ydsrj9hk2gpjk9hktmxam0r08zeny75dwlc7qxap6zk
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-26T20:00:33Z"
  mac: ENC[AES256_GCM,data:JZaZoj/jn8p90tFHYpgym6s9IOiQB2qMkV1YKVRG6e0sH9+RfjWSSOCXVbvQBCQ/npwrQa09Q9kpwWYPWpSvR4s2hbHWkhcXE8m1HjC1u3ZaLW19xS03jeLPnxYu04G6+T1CNUDNH10ZwxrLTDoDFL4qIrH9SUs3y4tzPjwBx8o=,iv:eZVrLB809sE+8E0xawNTPjm95sHporEsVSvC9b3+LJ0=,tag:O/RGnSrjLmDXlxgbaS0OsA==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
  name: printstash-secret
type: Opaque
stringData:
  jwt-secret: ENC[AES256_GCM,data:mU1YqvJZsO69Z6F8dpKQnFjPi40gL5OoYWkuwZ87KXWeJ58iE3MXTQcJkqXU0L1n5y9JBj1D2AoZba3+UV4wIQ==,iv:qFIzndn//BDO5PtMFJROH0gqyEv8JT2Lj+t5nF6eEBw=,tag:fpeW5kKhs8VUKEe4OOCOrg==,type:str]
  oidc-client-secret: ENC[AES256_GCM,data:GKXoeaMGZ3y20QQBWpvmTfKRrVABpVmh8MN0meT0yfs=,iv:IAu236FLDcG3UZ+ZWgCx53H9Og1szIhw9FVaHD35mnY=,tag:K3Eml29+EEj/TEIVEA/hCw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHWEJ5YXZQcXNab1lnVzJt
        NG5aOVJMU21rZDVCTkYyQTJjM2w3TG9semx3CjJSR1hwc1d2bnFjQ0QwMi9oa2FH
        R0YwYnorQlJUcGNqbHRyNXRSV3N4WUUKLS0tIGx4ZDdDVjhHVXRqL1Iva3drRkZF
        cWJYSm5sUWhBaFJTZ3VsY3YwRUJsNG8KCZa/FPUH6o3JTlahbYRU1z1WsTVQ+fdZ
        Lz2xepMmy2M6Zt4qY/7R/miMHo/VZOtSMRzk2ovqKG2cOxV/U24pWA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age13ttsf4ee2xr4e90ydsrj9hk2gpjk9hktmxam0r08zeny75dwlc7qxap6zk
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-26T20:00:33Z"
  mac: ENC[AES256_GCM,data:JZaZoj/jn8p90tFHYpgym6s9IOiQB2qMkV1YKVRG6e0sH9+RfjWSSOCXVbvQBCQ/npwrQa09Q9kpwWYPWpSvR4s2hbHWkhcXE8m1HjC1u3ZaLW19xS03jeLPnxYu04G6+T1CNUDNH10ZwxrLTDoDFL4qIrH9SUs3y4tzPjwBx8o=,iv:eZVrLB809sE+8E0xawNTPjm95sHporEsVSvC9b3+LJ0=,tag:O/RGnSrjLmDXlxgbaS0OsA==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
