apiVersion: v1
kind: Secret
metadata:
    name: printstash-db-secret
type: Opaque
stringData:
    db-username: ENC[AES256_GCM,data:l/FSynCB2QMGCA==,iv:MRA6fnMrUyNZymE6hLDTgwVIza3QOMIyweX+sUFEylw=,tag:IEsLjJAtL7cLQtAFV40DMg==,type:str]
    db-password: ENC[AES256_GCM,data:4Q5UUvamwc8tE0LpqD+8a63iND8YaKJhhUdmQzly6rA=,iv:4oin097HQ0JQ2Ua+twA/Snd5rrrdPtjV+9uTf/B1wLQ=,tag:l0PS2QgWCbkRAsPX8p1Sxw==,type:str]
    db-url: ENC[AES256_GCM,data:DgFh52H2DsiJuOE6j+VP3qD2A5FuLloPqHfdizPF+qLgc6vFXXHdTd2aFe0I11GJWDPr8IBFZJahUZe93feqkbWdk2anVW60pHnzAbpYG6ByvsFtXOXruBWdbki9EVDx9KUNkz73cnAX54UTqZw2qQ==,iv:Uh/coxkYZbANXHoj+ck1qGV2lcdJq71GYui9+kTW1XU=,tag:MBgWTgFI59iKw0rrvq/ubQ==,type:str]
    db-init-sql: ENC[AES256_GCM,data:DbIEF12nqhZeJ9TIvJ/qDLuHzss3FX4sT2N4iSJuTOFTRhaIdoKgJsdb7y4rj4g60LL6EUmzxn23299ir422hlxZ3wUgv9WQhG+18pdvpslEH0KtTyKgYLEv4YLFTAnEetstOXS3BzOhUxy28x4E3GZBbb93RR6/769L38qlIwaqZk1X/3YsFVzaOvF4IVJUyHfIJZRUY3OTTGEFCL+LWTAhJdETAj1+eBjOheMffCsoNANPk0/8qE8Nug==,iv:DZ4nuMyEAFv6iC5/MSj+HRvNc2ICSNf2kv14t7h1cYM=,tag:AAptps9zPmZcrwSXHzXScw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLb01oWXVaVVRwYzlKTFVQ
            RW9hSWpuWSttTS9uWWtLVFdDcGZ1a1hkYW5RCmxUcXBiV3dtRHFSa283MmVhUWZH
            TUI0djdybE83VEZ1Qzd6TlhGZktQTHcKLS0tIDIzaXlWNWtuNThsT3hYY2hrNDg1
            TnpIelVXT1ptNGRUTEtrcWhPbzJmQjgKK8a5TXGs63U5or6kxROX50yynDJY8d9h
            AoufC9TVq1PCov2JO2cvmjdqLXN5DOGz1OLbEGBZ1oE0WTqj4W+plQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13ttsf4ee2xr4e90ydsrj9hk2gpjk9hktmxam0r08zeny75dwlc7qxap6zk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-26T19:37:04Z"
    mac: ENC[AES256_GCM,data:w3qTEP//IoGGcwzxZY/iEIhH/JWoIatW/WJ0II44WdkPvb6yPbfrR/oV9cCvYuqmAlIZmMQ2e1epxBxwDRgY43yYxach32Y9MehbyyS+DmgWELvVHQC/tmBrid78PZMps24nsnBac5pAqqFxmK7+CgzH0H3uBUvLcZq9uIdKkiI=,iv:ihLfblvyzydB4Vz4lSLjHeYLbMWKc3BMXSMivBrKmXA=,tag:+GU0NZICKRA7Rca19WzDFA==,type:str]
    mac_only_encrypted: true
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: printstash-secret
type: Opaque
stringData:
    jwt-secret: ENC[AES256_GCM,data:EHECHSyKr+XyVYzqtm5mYPFdb1kklmcwwU2app/nBw3miC66mB3/1AdnnI1wLMI6vfFwiiNGRNOz3qDg7ys4aA==,iv:aQw+ZspIpDsmATEzM9nmh88kUxpsFKLsH304Zmp4+aQ=,tag:haks3jTOenu71O2enmsi8w==,type:str]
    oidc-client-secret: ENC[AES256_GCM,data:cjFOW8JUkKDiBaa3BNDdkwSTy3Q1ZEQlxcH1LpE8uAA=,iv:6ejqezjhxRuNBfPbcRyXlpHZsOcCdqorxJn/NQeTipY=,tag:T+aJctWtjkYnTCeYHIz94w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLb01oWXVaVVRwYzlKTFVQ
            RW9hSWpuWSttTS9uWWtLVFdDcGZ1a1hkYW5RCmxUcXBiV3dtRHFSa283MmVhUWZH
            TUI0djdybE83VEZ1Qzd6TlhGZktQTHcKLS0tIDIzaXlWNWtuNThsT3hYY2hrNDg1
            TnpIelVXT1ptNGRUTEtrcWhPbzJmQjgKK8a5TXGs63U5or6kxROX50yynDJY8d9h
            AoufC9TVq1PCov2JO2cvmjdqLXN5DOGz1OLbEGBZ1oE0WTqj4W+plQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13ttsf4ee2xr4e90ydsrj9hk2gpjk9hktmxam0r08zeny75dwlc7qxap6zk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-26T19:37:04Z"
    mac: ENC[AES256_GCM,data:w3qTEP//IoGGcwzxZY/iEIhH/JWoIatW/WJ0II44WdkPvb6yPbfrR/oV9cCvYuqmAlIZmMQ2e1epxBxwDRgY43yYxach32Y9MehbyyS+DmgWELvVHQC/tmBrid78PZMps24nsnBac5pAqqFxmK7+CgzH0H3uBUvLcZq9uIdKkiI=,iv:ihLfblvyzydB4Vz4lSLjHeYLbMWKc3BMXSMivBrKmXA=,tag:+GU0NZICKRA7Rca19WzDFA==,type:str]
    mac_only_encrypted: true
    version: 3.13.1
