apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:zOHKL1bEDPhQKwftWlz4VlSM0JqALd3kZj8nkh0qYSljXCkZ8eOF/w==,iv:0ZOMuowBc4g7QbSzQwirAwFKpi/olpO1IQaUuFkSYSA=,tag:ZRc+eN6VXqw6UatKtQfz3w==,type:str]
sops:
  age:
    - recipient: age13ttsf4ee2xr4e90ydsrj9hk2gpjk9hktmxam0r08zeny75dwlc7qxap6zk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcEpJckNRbCtSckZmN1Yz
        c2VadW1YVk9HN2M1VUt6NGlwS01NMmkrZUFzCkdkZHowL3MwZWhJUWVaTFZxWGoz
        TkpwcUV6VTBGSFpJQ2p6dlhVK05INzgKLS0tIGE4Sk02VGZPeE5Bd1BBMlJDWDJJ
        cERFU3E2My8yak11ZlFEWWg3MU1PR2sKAFfU3R8woeK81cbiKncZ/ZkD8YP53ZgV
        hb9jSbKLqYTPOzjWyy52Uf7wwp1Tk1maStsaVW52xhgD2X7Ul9TZDw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-06T22:47:37Z"
  mac: ENC[AES256_GCM,data:IR7MtY/dGUQKv66XuuCwgXEfzWb2r+qjHMVIbWy4VNP+CfUPF5aTwyXKzx6pw9kYxxnvjruPM78MrYeyVC2dnh6mng6qbQ9NxeJ25Ahx+o9cJGKW9abQF0uhOuQsKgk+uqtDuThxvgox3lm1s1403b2Z3nKGIuDjP7fyk+oHOYA=,iv:PRd+tAytJ0Qvl5JAK3mOLOEExEFQHNJBCtW9YR1J5Ak=,tag:jH3Dnokfn81o43ojv96KDA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
