---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: 3dchi

components:
  - ../../components/sops
  - ../../components/repos/app-template

resources:
  - ./namespace.yaml
  - ./spoolman/ks.yaml
  - ./manyfold/ks.yaml
