apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:9iZwuVjLrQcw,iv:GNHXAbblD+WuE2F6hSjSrRsgZ9oWmbo19p/QvzQg/zs=,tag:sQ0Ps3HTMVJ7h9et7gOHMw==,type:str]
  NFS_HOST: ENC[AES256_GCM,data:4o3GjP39pbYQig==,iv:jRAVb7knEds0DVR2xBlMTSvl5trLetturGQ+eLpAuts=,tag:+LOWIzeg+ApsYcKuJGQZmQ==,type:str]
  GARAGE_S3_ENDPOINT: ENC[AES256_GCM,data:mpBCnU1QKNmPUR1AHIKunnARGpD0WWw=,iv:js0pQdmcWEF24/ZsR8jfIM0I/coyLCl/B5MYhv3vG40=,tag:t7YOS3+YxnK+NFZY5BTa6w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvaUxBV1BDV3YwaWRESysz
        Z3dBR1V3TlljMXFSUHcxZWt1bXR2UGdOQlNFCmVIT21WUXJWaENxdzYyNFk0b1Rl
        THF1RVM0cHE4VXVjL1piRFV4TW1JR28KLS0tIG4zRjliNkZFUUhWa1lZeGR0SlAr
        Ujc4OCtNN1M0SzFWSTZzbldnQ1lOOTgKuvk6ji6u07FN7uR09b6OtH1L/z+Szmb1
        sPagtgbVP7oPpE8/J1uzMKzhRojOLRO0jU4mks3maNP3O5DT/x16hQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age13ttsf4ee2xr4e90ydsrj9hk2gpjk9hktmxam0r08zeny75dwlc7qxap6zk
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-02T16:27:22Z"
  mac: ENC[AES256_GCM,data:z8W44ZxzWyR0uXh9xQrw/Hs0+h2sPkpsSt/mE1gW/PxdS0bVqAaoAdnoCUH4Omk9wdsqrlfLFqlZa0igScgwL2NdFGtYQOgNpkPVL4jkn0bX1z6O/2jDGV540Rlk8benBmZe1l69qz+uuc7/oAz/NrxFsmTJ5JWBMRb8pz2itxY=,iv:7XRKj3D2CAoaJy03onhgbDyC/WoHiq2a832zQFeIT30=,tag:e+PPGduUVJoUBR89RY+M7w==,type:str]
  mac_only_encrypted: true
  version: 3.12.2
