apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:9iZwuVjLrQcw,iv:GNHXAbblD+WuE2F6hSjSrRsgZ9oWmbo19p/QvzQg/zs=,tag:sQ0Ps3HTMVJ7h9et7gOHMw==,type:str]
    NFS_HOST: ENC[AES256_GCM,data:4o3GjP39pbYQig==,iv:jRAVb7knEds0DVR2xBlMTSvl5trLetturGQ+eLpAuts=,tag:+LOWIzeg+ApsYcKuJGQZmQ==,type:str]
sops:
    age:
        - recipient: age13ttsf4ee2xr4e90ydsrj9hk2gpjk9hktmxam0r08zeny75dwlc7qxap6zk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvaUxBV1BDV3YwaWRESysz
            Z3dBR1V3TlljMXFSUHcxZWt1bXR2UGdOQlNFCmVIT21WUXJWaENxdzYyNFk0b1Rl
            THF1RVM0cHE4VXVjL1piRFV4TW1JR28KLS0tIG4zRjliNkZFUUhWa1lZeGR0SlAr
            Ujc4OCtNN1M0SzFWSTZzbldnQ1lOOTgKuvk6ji6u07FN7uR09b6OtH1L/z+Szmb1
            sPagtgbVP7oPpE8/J1uzMKzhRojOLRO0jU4mks3maNP3O5DT/x16hQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-31T18:26:05Z"
    mac: ENC[AES256_GCM,data:YkgegJYndLEVMWyunr6CDwkvL3TXPl/bZhyTpcQy4ec2T4Mca81WyZ0Etc4RzZGrPIXIFpaymZGKURqfjBrkZ2yhB1VnrUz348IZgI4m1Xd5SgI70RV3iT12afOFSuRznIPVJOPp4QxD1rwCcV7Hfs8LUrDmBJzxf1z0PBpWHmQ=,iv:QPlxWhoiTfbD33KBfM5meeeMKXJCChN2pXCQ7RxVcgU=,tag:vPIS4WN+9qpS15S/uNJ16w==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
