apiVersion: v1
kind: Secret
metadata:
  name: forgejo-pull-secrets
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: ENC[AES256_GCM,data:lxJqMnYnFzic57foT8nr76wacKdAgf7YjrhJjBz9gcSbHHGwFEAj16TQf+k9lh4ThgY8G94MLCpMqytGYwjhmmIe8QZ6uvGsiojvYh59MgunqZISDGmRoqZY4NFqDQKIIUyPx7Sr3dTPKSx2NU+GOZQQDHVvK2gkNuUYCWbpjrv/W9Q9xJ8qORYrcI/4v3lIlRzn5eIvmUDaVYtTjwVuiYAow9W8IodFvsey5YwEWHU0ErlX9+Vpgzc=,iv:XrYJ6/t9IHjQ/apHCGJX8EjrROb28T3m17b57ujIpXo=,tag:9NoEC6JNLESDTmVXARxO4g==,type:str]
sops:
  age:
    - recipient: age13ttsf4ee2xr4e90ydsrj9hk2gpjk9hktmxam0r08zeny75dwlc7qxap6zk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1eERIemlZYlZibG95Uk9K
        VHZRWVJneFFiaVNrd3VsTVpXSkdPeE16MVFNCk9NSktLb0dxSmlIeUFYcHNFdUl1
        d2NYYUpJT1NNK2M4ZDdyMzB1dXlaVncKLS0tIC9RcldyV01DTGlaekdhb0J1bkpU
        dXRCcWdYVWRNekxjSnlZQmxCOXFGd28K2kQIWKh4AGm5Z46fCPx4kgbOKRfCC8Ay
        DPDMAhzOToXN2yol/pSI4j+/s6T6YyA/MCn8T+9RJ5LK6t+E7syxWg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-07T02:41:15Z"
  mac: ENC[AES256_GCM,data:ysR8bBObKRKEHaUXHrxe1BVaDiyPWWV9snaIHnm7XYJW+UU4ScOeWayRl57Lv9cA1lp23N8DtOv0/FodUiXIsisxx0xO38E7xPEuzJJUxAFM9J+V4GXT4frHqFn1AQVOXr9ETPmXttHAA7EHbo9FRoY+/jXaHs4tLpVmRSE6LzE=,iv:XzRNF61js+92G3wtKYNYLcPrj/7PuELylJhsI2gPCGc=,tag:LtWFqUSjU5Ds6qXySvL7dA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
