apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-pull-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword

  target:
    name: forgejo-pull-secrets
    template:
      type: kubernetes.io/dockerconfigjson

  data:
    - secretKey: .dockerconfigjson
      remoteRef:
        key: forgejo-pull-secrets/dockerconfigjson
