apiVersion: v1
kind: Secret
metadata:
    name: gitea-admin-secret
stringData:
    username: ENC[AES256_GCM,data:8rb1OPA=,iv:58W6uj+dD3NdiILMlz1r8c7+U7A/NOxHBhMTH+xvDgw=,tag:cQ4gt1iTIhtNiIewm9ytFw==,type:str]
    password: ENC[AES256_GCM,data:BgfrxDggkyZCRw==,iv:v1pIX0TYrNx/Bm5cbizljhuKyoWfYLvh9Ni3W+NMC8s=,tag:t+V+PRf4Su20L0eQF3p/wg==,type:str]
sops:
    age:
        - recipient: age13ttsf4ee2xr4e90ydsrj9hk2gpjk9hktmxam0r08zeny75dwlc7qxap6zk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4TWt1WjR0NFJEdHNsNHl1
            Tzc2S2ozdEZsazd6eEtpTlpqajd6SzFJdkVvCmx0RVNFVnd2OE55Z2tUMzByeUJS
            STR3VHhtVmNlYUxYMXlWMm84YmdPU2MKLS0tIFhuTGM5UHZqUW9DaENHcXpRdlN6
            TmxWREVPVFhzMWI4QXdpcUlpL3l6c2MKysVHArMBoq2jl17P77bCFFJfhWWKEvrT
            ZZqBMUoi++CHhtFLkdInthQ6bp6OHmXTIE8DKZbqpiBcUwNa6RxYtQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-08T06:00:59Z"
    mac: ENC[AES256_GCM,data:58SdbJRph5bcHbKuGpU3ygEnj/DLLeDVnFe5FvM46ND7Okhnm8prcTvEWY6T8hM1xACq9eY6TabaNHWLwIJb0DSMI9dDvr3oishG/DuzQNioR8U9ucryRbktn2w5M3mEUyPUhTk3BjD0X4L7tA6WH6w7kkhaG88qAQvgzkvDwJ4=,iv:CtxhZxB1uA5Ah2ROqOvBCij91UgisElZ0t8YQ7dudKg=,tag:pzpi6r6iA5iBzdAEN91slg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: gitea-config-secret
    annotations:
        # This is required if you have $ in secret values to prevent kustomize from substituting them
        kustomize.toolkit.fluxcd.io/substitute: disabled
type: Opaque
stringData:
    database: ENC[AES256_GCM,data:OhGRe2D7pLNWNBBRGLbc1k1QougSJHApKPWH9BuWK4yA2Nukpyca7CGhvSIq7zVFcDs=,iv:ZaMo0WJ4LsulGky77V1FXRk8cR+qPRNTxqN7p4imq/Q=,tag:b+qf6nUh96knTjxfk8A9SA==,type:str]
    queue: ENC[AES256_GCM,data:neG3l7pY0kdzVKYOnd7ZMk7i7kBVEq6NHlxj++J+ua09DsdET46NdRqsB6XhsINg1/dQ6BjCSczqyPqNnb1TX4Q=,iv:FNBjEmfheszPcs3MhG+aOpjsyhmsh8wt249DqcH2Ejo=,tag:Bg0CMKHwPf8EemN0jighzg==,type:str]
    cache: ENC[AES256_GCM,data:iQrZlKPOYM4Owql4n3xTEhle26tQndx6Z0FqNGlfBNFazjyR0nL1TR/oImNvzohtWb8vTIiIJfFWyuPyyE7qMu7kVXIIuTD/toDfGIrPCzNUitJIJZmO6mNfza+PxiDQ,iv:0g1H1he8CvcyzcYj68OIQKpq38Y6NDJqLj1Y8GR+9ac=,tag:i/R+gisBulgYUFXBWode3g==,type:str]
sops:
    age:
        - recipient: age13ttsf4ee2xr4e90ydsrj9hk2gpjk9hktmxam0r08zeny75dwlc7qxap6zk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4TWt1WjR0NFJEdHNsNHl1
            Tzc2S2ozdEZsazd6eEtpTlpqajd6SzFJdkVvCmx0RVNFVnd2OE55Z2tUMzByeUJS
            STR3VHhtVmNlYUxYMXlWMm84YmdPU2MKLS0tIFhuTGM5UHZqUW9DaENHcXpRdlN6
            TmxWREVPVFhzMWI4QXdpcUlpL3l6c2MKysVHArMBoq2jl17P77bCFFJfhWWKEvrT
            ZZqBMUoi++CHhtFLkdInthQ6bp6OHmXTIE8DKZbqpiBcUwNa6RxYtQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-08T06:00:59Z"
    mac: ENC[AES256_GCM,data:58SdbJRph5bcHbKuGpU3ygEnj/DLLeDVnFe5FvM46ND7Okhnm8prcTvEWY6T8hM1xACq9eY6TabaNHWLwIJb0DSMI9dDvr3oishG/DuzQNioR8U9ucryRbktn2w5M3mEUyPUhTk3BjD0X4L7tA6WH6w7kkhaG88qAQvgzkvDwJ4=,iv:CtxhZxB1uA5Ah2ROqOvBCij91UgisElZ0t8YQ7dudKg=,tag:pzpi6r6iA5iBzdAEN91slg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: runner-secret
    namespace: default
type: Opaque
data:
    #ENC[AES256_GCM,data:+06SF7aBiVy+zoksJMYs77xxEzM/kHo6uShcodyjPb1lvyLsoGs7E+PiKTBXZ/v2cHYtSzr2d3/Pwkhk9t6uRFP5IsduIogtiH2Qg/I=,iv:V2Sgle5Vu+u+i5OTzLJpxaJIK0CcdQ5dvKtZipq7+5E=,tag:sMyzs0aHpEVh8JUUP2LhHw==,type:comment]
    #ENC[AES256_GCM,data:Eapw572b8L3MZWtWBG6ALvot887UK6uuQKbnQaDd20xfrjJyXs48GpEvkMCYbr+WMkMJtf9J2L7nb8F8VIgTBv8ZR8jkLEaE7+MSBbbU9NNWgwWuOnvSyoMnnxw=,iv:xcjVKdMOFbqcfVSRNF3ngw4YgfUYhL/SOI7v0er6RHE=,tag:XEBbYDH96J/VdGteys41yA==,type:comment]
    #ENC[AES256_GCM,data:kZvZWkibexCOdzfEmwl9yRLu0la28k7Vj8zeGYosQxALNmwwn5aCUhR8LjzVmNNlM5cnmYZLDPU6mQwK0/gEGeHdBikAbGO6nO5PSwRKV7opYUMlCACf53q1zdondHA=,iv:c1vWmthXANbege4EYrfUCqq2rgtyHzLr4v0S8fZeQ20=,tag:IxzIF2RtrdLFsxammJ8sUw==,type:comment]
    token: ENC[AES256_GCM,data:8qsPoPUKHKOlRc7grFNv4deDYVuFrTi5uCPA/B/pjyVNZFT9zPmcj/eq/uGoUSGmkMqXoy+Bwm0=,iv:xzc610m/99Ds1QHFNN71bHkdt0vXvAydWsAAgMCVvBM=,tag:Gkogr1/WqSTHCcZ7IEY9+w==,type:str]
sops:
    age:
        - recipient: age13ttsf4ee2xr4e90ydsrj9hk2gpjk9hktmxam0r08zeny75dwlc7qxap6zk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4TWt1WjR0NFJEdHNsNHl1
            Tzc2S2ozdEZsazd6eEtpTlpqajd6SzFJdkVvCmx0RVNFVnd2OE55Z2tUMzByeUJS
            STR3VHhtVmNlYUxYMXlWMm84YmdPU2MKLS0tIFhuTGM5UHZqUW9DaENHcXpRdlN6
            TmxWREVPVFhzMWI4QXdpcUlpL3l6c2MKysVHArMBoq2jl17P77bCFFJfhWWKEvrT
            ZZqBMUoi++CHhtFLkdInthQ6bp6OHmXTIE8DKZbqpiBcUwNa6RxYtQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-08T06:00:59Z"
    mac: ENC[AES256_GCM,data:58SdbJRph5bcHbKuGpU3ygEnj/DLLeDVnFe5FvM46ND7Okhnm8prcTvEWY6T8hM1xACq9eY6TabaNHWLwIJb0DSMI9dDvr3oishG/DuzQNioR8U9ucryRbktn2w5M3mEUyPUhTk3BjD0X4L7tA6WH6w7kkhaG88qAQvgzkvDwJ4=,iv:CtxhZxB1uA5Ah2ROqOvBCij91UgisElZ0t8YQ7dudKg=,tag:pzpi6r6iA5iBzdAEN91slg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
