apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:LiF4U9/J6GL1pwLQ99/wkspbUBRGjIevofGHxif34L0=,iv:vG79XSbwLEOmgPYGUXTfHUTOGLZB6PwsFYWyekmxsUg=,tag:kpOIO9NGZKurrVxwlAlQNg==,type:str]
sops:
  age:
    - recipient: age13ttsf4ee2xr4e90ydsrj9hk2gpjk9hktmxam0r08zeny75dwlc7qxap6zk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTN3JveGRzVnZkQXZCazh3
        d2tMU3hzTWNkaFVkc1pqd1RaMXl5R09BckVvCmNEOXBZcXlwYXJabFpiam9GUklY
        RXRRcklFTUNXQXVkd3hOOWo4T0lLTHMKLS0tIEFzNkJHNmx1bkhpWWVFd0Vwb3Fo
        TjRLWXlpT242cmxCSU1raHIwcXpNR2MKjYFX0NyiJ5SOJ6EQoSAIFPssT+JwAzDg
        BNgu6GziL0CV037BkQvZq7W590nCZF66+t9s6KndPsCwbIwLns2G3Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-06T22:47:37Z"
  mac: ENC[AES256_GCM,data:uGd1WM6mzXzTfu1pLIqz0ycvs/YCQltZXTxaxvTCpFLgd8FFi1lJJ3+u8RBx4+rP0dUc6ZdfBxAqk3VeIewBFQIac+YFreOMwYeGE3r0XdNpkmcixOYLQ2lUzniYJYngM0+R/acG2/T8vf0TSph9LQ+9pLFEIJOx3YCnIKvmVEo=,iv:wfUE7g1b+saAd8Y9jaTNjuLU4y7vYYTKY6E7WICpr4E=,tag:2cFbgufu5Vn3SrGRouyxDA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
