# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-secret
  namespace: observability
stringData:
  admin-user: ENC[AES256_GCM,data:xu1NJzkQ,iv:p+cN8pGKO0bakqoBi4qhDHGMJ1e3RnKdpJMds4XIils=,tag:UxZsqNaTIUIFmN2pha6+PA==,type:str]
  admin-password: ENC[AES256_GCM,data:GGzKPhkBFwFIWA==,iv:FOIMQIkYYQ9hri9j8aIfeNwEUrh+MulGhzZXoidQK4M=,tag:i0m2yfFqnFQDMZx4JbGLNg==,type:str]
sops:
  age:
    - recipient: age13ttsf4ee2xr4e90ydsrj9hk2gpjk9hktmxam0r08zeny75dwlc7qxap6zk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3Y0ovaVFJSko2T2NURFRN
        TldxelYrZ1lFQnZNQTF4NHIrVTdMV0R5WVNnClYyakNRajBESlAva3VXM0NnNXhp
        ZDM2Vnk4YnNCSmdtUnUvd1RHenBwRWMKLS0tIDRONlBEaDJLQjI0MFJ1UEhMSzBp
        NlM5SldXY3RnQ0hHMHkvcDdqeXo3S2sKFNSDOBisQF4lvLaDg1MBmEhwuXDABvat
        WhLjrv/B6AR4LxSu0ihSBUQEesBi4c+JWvBAbJceVG5RnC3CEWBezw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-07T00:48:42Z"
  mac: ENC[AES256_GCM,data:HR0h1Y5Hxh86X1pcQJ4B5tcaEb53XKrYZ9V0BU9tCRQHTPfsuOqH53MuF+J/mdUKKVOVueTglgiqIi7noxQgMylVl8oTMDB2CmaTlsK7LR8NtBgFk2NSVtlij8x7NwomPFewaGYayEQUs2waOL5bfJXeNoEvhKZgVBNc8eLMyB8=,iv:XgB4iWCLXIvh+q1A9noEA22erYcUQh/ewUxCMzgkZUg=,tag:kDeuj+mBT46TAbHF8KmEeg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
