apiVersion: v1
kind: Secret
metadata:
  name: sonarr-secret
stringData:
  SONARR__AUTH__APIKEY: ENC[AES256_GCM,data:uwCBF3sCpSUlZkZzEdrBcTnj00628ByQ,iv:Q5jL08bp0xubl2E7Q806DDviTER57ogWkfGxuiFHmDI=,tag:eIbk4MGVzLMsY8SvJPvjSA==,type:str]
sops:
  age:
    - recipient: age13ttsf4ee2xr4e90ydsrj9hk2gpjk9hktmxam0r08zeny75dwlc7qxap6zk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2eVI2L1NKUHRPVFNUNEtF
        V0VYcTE2UzRxczFOMTdicUUxUzRwRjJ3a0YwClJ1UFdXSXVZSnNNcENJOXI1K2du
        dGxXNkZGdWdGakcwY0xRNDdieldFK00KLS0tIGpLQjR6eTdHTEo4bEZiRTc4NU9j
        MXIzMno4Nm5lMyt1REJtZmMrQlgxZ2cKwd9k0zjPNTt6MH0xXYDPCTcPw2R540Qp
        86KGDilCIPBQqP5kDJwSNw8ZQGqoq2ZdBoC6poJHB2bs/d4dDD4XuA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-09T22:08:47Z"
  mac: ENC[AES256_GCM,data:ERZm2HtrI7mHnwLAmUkcJH1HQNurMTFR2PIzjFuvudQXkoYEjK5on/p3IMbpG9yKzde2uZDs5z+ig4JG5OnM/cfNNxw9qkSkD1Oy2LchmkRkqTc0NtwtuFAt8Xs1pczo+0B3JSWlXyZIsSwvV1orMrfm4bfxb2pUOESfINzmSVA=,iv:zrfyAjyjURnsFevpTb8qFPCNIcXkKmSf/ihCRis/bdw=,tag:XPSpTK6cfLcfmRJ2jJWPmQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
