---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app busabase
  namespace: &namespace automation
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 1h
  path: ./kubernetes/apps/automation/busabase/app
  dependsOn:
    - name: rook-ceph-cluster
      namespace: storage
  postBuild:
    substitute:
      APP: *app
      GATUS_SUBDOMAIN: ai-base
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false
