---
apiVersion: stackgres.io/v1
kind: SGCluster
metadata:
  name: dash-db
spec:
  instances: 1
  postgres:
    version: '18'
  pods:
    persistentVolume:
      size: '2Gi'
---
apiVersion: batch/v1
kind: Job
metadata:
  name: dash-db-init
spec:
  backoffLimit: 10
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: OnFailure
      initContainers:
        - name: wait-for-db
          image: postgres:18
          command:
            - /bin/sh
            - -c
            - until psql -h dash-db.default.svc.cluster.local -U postgres -c "SELECT 1" > /dev/null 2>&1; do echo "waiting for dash-db to be fully initialized"; sleep 10; done
          env:
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: dash-db
                  key: superuser-username
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: dash-db
                  key: superuser-password
      containers:
        - name: init
          image: postgres:18
          command:
            - psql
            - -h
            - dash-db.default.svc.cluster.local
            - -U
            - postgres
            - -f
            - /scripts/init.sql
          env:
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: dash-db
                  key: superuser-username
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: dash-db
                  key: superuser-password
          volumeMounts:
            - name: init-sql
              mountPath: /scripts
      volumes:
        - name: init-sql
          secret:
            secretName: dash-db-secret
            items:
              - key: db-init-sql
                path: init.sql
