---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dash-oidc-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword

  target:
    name: dash-oidc-secret

  data:
    - secretKey: client-id
      remoteRef:
        key: dash-oidc-secret/client-id
    - secretKey: client-secret
      remoteRef:
        key: dash-oidc-secret/client-secret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dash-db-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword

  target:
    name: dash-db-secret
    template:
      type: Opaque
      data:
        db-username: "{{ index . \"db-username\" }}"
        db-password: "{{ index . \"db-password\" }}"
        db-init-sql: "{{ index . \"db-init-sql\" }}"
        database-url: "postgresql://{{ index . \"db-username\" }}:{{ index . \"db-password\" }}@dash-db.default.svc.cluster.local:5432/dash?sslmode=disable"

  data:
    - secretKey: db-username
      remoteRef:
        key: dash-db-secret/db-username
    - secretKey: db-password
      remoteRef:
        key: dash-db-secret/db-password
    - secretKey: db-init-sql
      remoteRef:
        key: dash-db-secret/db-init-sql
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dash-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword

  target:
    name: dash-secret
    template:
      type: Opaque

  data:
    # openssl rand -hex 64
    - secretKey: cookie-hash-key
      remoteRef:
        key: dash-secret/cookie-hash-key
    # openssl rand -hex 32
    - secretKey: cookie-block-key
      remoteRef:
        key: dash-secret/cookie-block-key
