---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forgejo-runner
spec:
  chartRef:
    kind: OCIRepository
    name: forgejo-runner
  interval: 1h
  values:
    runner:
      config:
        create: true
        existingSecret: "forgejo-runner-secret"
        instance: "http://forgejo-http.default.svc.cluster.local:3000"
        file:
          log:
            level: "info"
          runner:
            file: ".runner"
            capacity: 1
            envs:
              DOCKER_HOST: tcp://127.0.0.1:2376
              DOCKER_TLS_VERIFY: 1
              DOCKER_CERT_PATH: /certs/client
          container:
            network: host
            enable_ipv6: false
            privileged: false
            options: -v /certs/client:/certs/client
            valid_volumes:
              - /certs/client