apiVersion: v1
kind: Secret
metadata:
    name: forgejo-runner-secret
    namespace: default
type: Opaque
stringData:
    CONFIG_INSTANCE: ENC[AES256_GCM,data:XZvNBxVx4ka0l/u98lSAs/lTa4FGIbbN2NiwEoCPZmJ5Z6zAY1JdM/Hy+Qa7HD25SFA=,iv:V8FKCJ09L/0yxTOlb3W9ihbfEWdYXs9tw/3kzbEpyVY=,tag:V2UinAWXpmHIX3z0jln/hw==,type:str]
    CONFIG_NAME: ENC[AES256_GCM,data:pJmUCs7jdw==,iv:8svVst4+vSsfZ18Q0n0OzXtPLZFSN+YputQkfVHAW/M=,tag:utxAZXQ1W7zoEKFAdU2acQ==,type:str]
    CONFIG_TOKEN: ENC[AES256_GCM,data:fj//itgUSlMKSjFtJUpBZpQztj2Eh7nO4EqUk6fFe9lgPkHiEtrqRQ==,iv:dyparrPNVEz+Usqkh8kuYdb4rZ0Hyk6i1nzrRZ/paVQ=,tag:dXfjLc67aMloIQQq/QTOZw==,type:str]
sops:
    age:
        - recipient: age13ttsf4ee2xr4e90ydsrj9hk2gpjk9hktmxam0r08zeny75dwlc7qxap6zk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZeTlPSzZNMFF2UGlBazJL
            a3Q5NW1iNU13ek40dklJcUxqN21MOGhZaVZ3CmVyaUc5Rks3d212dDRNMVk3ekdm
            b01BMm0wVzJUNzRPSW9HUHpBL1UvYzAKLS0tIFEvWXBTZHhpUXJwVVJtUnQyOVZO
            M3QvS25RUmlWME9ETSs2UkpBUEtsS1EKbG2tBsiJgFqgVAUYOm08dcrSoLj0xDXq
            nec5SZATKDhn0DHKg5iL5hP3Z0hh3F9+FKSoNV9jMeveYtDilajULA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-16T22:43:57Z"
    mac: ENC[AES256_GCM,data:FxYpH2aH0TE5w0VQWFrneCQdIYEZEYcp131Km/4qd+sFfRQTRkC7B0SdgV8wzGUiR9bntvNA8neNCru0J2EDjM548WaIAp6xxAfBLV+oNdhKLasexQcNAIS05P0Dtek5KEd55acybkzxOOwUVyt9ohRgY7UJfNrP+NOKNRqWlKg=,iv:7+4R6lmvu0FYS+e5YAdp9BFoWcWB2+6NFvPaukZ9VLQ=,tag:E7Cv0Bfvt9VRDd3QpElUgw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
