apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: onepassword
spec:
  provider:
    onepasswordSDK:
      vault: k8s
      auth:
        serviceAccountSecretRef:
          namespace: external-secrets
          name: onepassword-service-account-token
          key: token
