apiVersion: v1
kind: Secret
metadata:
  name: onepassword-service-account-token
type: Opaque
stringData:
  token: ENC[AES256_GCM,data:v12YPljXxsm3EW5yIF5qoY3g5mUA27SPsd2E3TucyWML1ULTEAB26j8xppjllRjO5dXwN01ii09dUxuC+V3cgdIKgzdSkEKXxV6BKj+0XgyiF+mMKL0L0uWXTRsu5ZLWn4uhizyNIhDsZFjIPSBXq6AodegY0dT7r2tWCx2hl5egRp+TizsG/6Y0ejRJBtDV+xUFuecMaVP0uFFwgJ+lsiekIsmc8WSemHCXz0p70l3quUNhHBlHdixFgVtEmUSi9GZofKy/uZ56b8YO+RcX0Qy8KfK98YtHduaN7mZbc2upJA+Hb6NTBzPJRXYLQ4rnqWEjlOzp3IU9fnLW69Ml5sKJHfyaryG2kvDz8aoPfhkxgKpDGdDD6+PLtuRkh6V6Y2dTAoVsL7z5NLJ78K8Hg0nbRM9M8Yt9MgCOR9T/IgV4N93r+wge0VOLx42jrwIaDJk0K5YDgUBrq4ZwGEQSEPrPTnK0SBgeupUNa1N9awQDPwdxRVSTS3YPNYYDyLZfh9LRadHcmxeMkWOJfF2IcD1rJ669v17TuHKY3hFZezU3RkyKa82AJWZ20EQgshhslnp2IZikX0UkwImhvV7Wlz7rD5gbJAWt1geftGwrX+IpbRZjiArBmYYbjxdQ7Bi1YyUg9ina/euk53miYXYxfKtRFwhsGI0+D6TQOgiXJAJrN0Osc8Xj6Oxi5qRHQNsveSOlT91Wbs78IJr2iHaf8m6XgDON0fZbUoDN85upDOgX0fTwlUGMPKiRDGBLv47Rf0WAm2edJiLyfXeCU0pujU+iKHUnOEVskEMufK1ZrLi71gCcFQLu505IBiLCWarwQMx1OJ3Nf0jZ6y/2uKSCh5WmoI7TAjnxwHPt5oQ/K29NdlS5LvFW3oqPJqL7aPZi5CtgkR/9tC+cM8f6q5VcVPzd/9FVoMX82sflu8J1592cdbLVU49UtTvZNGM0+9AP9q0c6nep+Uvz/N+aEgOYyXnpWGWnebLubgcSRBdsekRxFJ9nBnb7hfYL8QxzHAj7nR0gaojl2iaprBV+VWxbFvJQIgKLSlj7WhaWldcqSY2WhXd1m+jnFq4FibliKCeyTL4X4T0unWB/FLdq7+l8yVkUEPUT3eZ7sHwpOlqCVHuf4uyB,iv:Cn9sQBni7itHkbh/og6s0omUhkn0KEh6mVo72DLuh2s=,tag:MPPgHKUDL6pV2HeED1P+JQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBERlZDSGY4Sy9Xek8xMVFL
        WEgyUWgxcEoxQlcxd09VbEpyMW5uT1pCbEdnCk5aSExOTDBDZlpQbFpyWXMxN3FZ
        Z0M0TmV6UHlwTmhCZXBaTk9rYkZldVEKLS0tIEdvL1BPL09kTUVTQlBYN2NZemx3
        Z0tjanV1R0NnUDA1MWZ6TklVY1VBVFkKD2T77H7fI50hK93a9VUhJ/8Td1qU/pNv
        XBUIg7ggr3Z2LLjW1VMklbFxTM2bWyCgYoUB7s/gQDgqv1YjdPTneQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age13ttsf4ee2xr4e90ydsrj9hk2gpjk9hktmxam0r08zeny75dwlc7qxap6zk
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-13T22:40:42Z"
  mac: ENC[AES256_GCM,data:CsUHG55toc4tgOmwpxfKquwL0mzEciMLQhfAbFi8EUnEYMs5VW+j0CNuXnwSi8xbTw+PkjSon4xLCEV6vGs0aBCaqssLodDMUy2xtr3Hf/vev62+9ghhJC0Vs6ZTylRELid3sDbqp/O7nVXhImMAucylj1blIPfyIYQlfvpcriA=,iv:bhKXX9PDBa6jctcSwJR08d15+Nlma3l+jmnit35DojQ=,tag:xsIkjnz4m0Ph6dCRZxyp5w==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
