apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cluster-n8n-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical

  target:
    name: cluster-n8n-secrets

  data:
    - secretKey: DB_POSTGRESDB_PASSWORD
      remoteRef:
        key: /databases/N8N_DATABASE_PASSWORD
    - secretKey: DB_POSTGRESDB_USER
      remoteRef:
        key: /databases/N8N_DATABASE_USERNAME