---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-db-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword

  target:
    name: n8n-db-secret
    template:
      type: Opaque
      metadata:
        labels:
          reconcile.fluxcd.io/watch: Enabled

  data:
    - secretKey: db-username
      remoteRef:
        key: n8n-db-secret/db-username
    - secretKey: db-password
      remoteRef:
        key: n8n-db-secret/db-password
    - secretKey: db-init-sql
      remoteRef:
        key: n8n-db-secret/db-init-sql
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword

  target:
    name: n8n-secret
    template:
      type: Opaque
      metadata:
        labels:
          reconcile.fluxcd.io/watch: Enabled

  data:
    - secretKey: encryption-key
      remoteRef:
        key: n8n-secret/encryption-key
