---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homarr-oidc-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword

  target:
    name: homarr-oidc-secret

  data:
    - secretKey: client-id
      remoteRef:
        key: homarr-oidc-secret/client-id
    - secretKey: client-secret
      remoteRef:
        key: homarr-oidc-secret/client-secret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homarr-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword

  target:
    name: homarr-secret
    template:
      type: Opaque

  data:
    # openssl rand -hex 32
    - secretKey: encryption-key
      remoteRef:
        key: homarr-secret/encryption-key
