# NOTE: anything on port network/envoy-internal.{port} will be routed here
# There is no "hostname" option for tcp routes
apiVersion: gateway.networking.k8s.io/v1
kind: TCPRoute
metadata:
  name: forgejo-ssh
  namespace: default
spec:
  parentRefs:
    - name: envoy-internal
      namespace: network
      sectionName: git-ssh
  rules:
    - backendRefs:
      - name: forgejo-ssh
        port: 22
