apiVersion: v1
kind: Secret
metadata:
    name: forgejo-admin-secret
stringData:
    username: ENC[AES256_GCM,data:/BdYyYRPed7hkrqK134=,iv:kKwpp77BzjtK9w+wi4ko8n/ZKGyY98KT3QLd21QJOOE=,tag:Yb5CdA0tE84FSJkWWEAUqQ==,type:str]
    password: ENC[AES256_GCM,data:BgfrxDggkyZCRw==,iv:v1pIX0TYrNx/Bm5cbizljhuKyoWfYLvh9Ni3W+NMC8s=,tag:t+V+PRf4Su20L0eQF3p/wg==,type:str]
sops:
    age:
        - recipient: age13ttsf4ee2xr4e90ydsrj9hk2gpjk9hktmxam0r08zeny75dwlc7qxap6zk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4TWt1WjR0NFJEdHNsNHl1
            Tzc2S2ozdEZsazd6eEtpTlpqajd6SzFJdkVvCmx0RVNFVnd2OE55Z2tUMzByeUJS
            STR3VHhtVmNlYUxYMXlWMm84YmdPU2MKLS0tIFhuTGM5UHZqUW9DaENHcXpRdlN6
            TmxWREVPVFhzMWI4QXdpcUlpL3l6c2MKysVHArMBoq2jl17P77bCFFJfhWWKEvrT
            ZZqBMUoi++CHhtFLkdInthQ6bp6OHmXTIE8DKZbqpiBcUwNa6RxYtQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-31T17:35:51Z"
    mac: ENC[AES256_GCM,data:zX3VWyG1apXJeX9bopuyaIWuuisw2ZewC0nOJCUWOBKpYtF0GMLlIJXuEuMwxa3MJD1qhGACKTPBP5V7MP/O19aHgWGKqz6J17YdV1/o1M1IoABBnn/UpzyleR+p7Q+Dx26HGp72c+vx4O7xo34EXtM76Vza3nYHcx/EUmSgxtc=,iv:33Gub/z7SHw43iihpvvq9yLyDz6Npajvitls7Bzkl4s=,tag:bMat8tVX5EQnKtOMiXV+Fg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: forgejo-config-secret
    annotations:
        # This is required if you have $ in secret values to prevent kustomize from substituting them
        kustomize.toolkit.fluxcd.io/substitute: disabled
type: Opaque
stringData:
    database: ENC[AES256_GCM,data:HoT69tm/vHQ88e7HmnNNiwLsn1lWnLHrornpAAOQsfI4r3RbwsRnZaRw2nlafWph9RF6wL7A05/9mExu/+RbFDcD,iv:cfZO4Xk7qe17H35zmfQz7zT+cVmq/fliUTyaZoYpm3o=,tag:+Bc+jOya1rCfl/yB810SJw==,type:str]
    #ENC[AES256_GCM,data:fyiEoXOxnKAf,iv:wc/htNq6zoNaJlJyAEvWbjL1sK7tMPcz+N1LUqlskM8=,tag:Xzl/vRb2ROpzmEMeZjNvdA==,type:comment]
    #ENC[AES256_GCM,data:tXwiYmH3A6vEVBVrBweh,iv:OQ67HpPB4hwCUASJQMJd0aev8Wjdp0bfDyYFlIO3XTA=,tag:1KfjL3Yk4Ti1u9VoCv1bCQ==,type:comment]
    #ENC[AES256_GCM,data:jtmqzm1gPSN/RgnTirX51msvRcBc1tcmgYQe1I0mozFj0wkD3HZag90GrFLwjpHwMHgvFBMegQhMZQ==,iv:YZ1ON8jhnSWVYBa6sfK1jhIoMBvEknzGupmyoeyTo9I=,tag:qAfsRVn7+AOeVxlXohrRjg==,type:comment]
    #ENC[AES256_GCM,data:ijVpWYnC+DM+,iv:gDWFPsyMQHpKnh9SLF7PAenqyS7aCKycZa1S9H14YPU=,tag:rbnhQcNG+t09CpawFERZyQ==,type:comment]
    #ENC[AES256_GCM,data:iYRR0c79ORCvFmmp0m39wCV+,iv:E/eNLOGhlW0aq73dVp0bCL7PRNQmojxCKPICuM/q4cI=,tag:g47bdamUUwIH0qDL3p26EQ==,type:comment]
    #ENC[AES256_GCM,data:2u/3C8P+wLCTxB7rub/zyI8Ap714On4Gk6v0sadlfOHQ14UeNbIkjyK/mbl6AJkt9+QNi79ShpfVOvoycJgJoOfp+PBEQ0FyHEXwZirB2jNttN+HidY=,iv:WxNVCeSGZCx3+1cJMq+y0ka4gHCG9uDIOwe8nYjlcnQ=,tag:KkxPujnsbNRsYHc/OoImcQ==,type:comment]
sops:
    age:
        - recipient: age13ttsf4ee2xr4e90ydsrj9hk2gpjk9hktmxam0r08zeny75dwlc7qxap6zk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4TWt1WjR0NFJEdHNsNHl1
            Tzc2S2ozdEZsazd6eEtpTlpqajd6SzFJdkVvCmx0RVNFVnd2OE55Z2tUMzByeUJS
            STR3VHhtVmNlYUxYMXlWMm84YmdPU2MKLS0tIFhuTGM5UHZqUW9DaENHcXpRdlN6
            TmxWREVPVFhzMWI4QXdpcUlpL3l6c2MKysVHArMBoq2jl17P77bCFFJfhWWKEvrT
            ZZqBMUoi++CHhtFLkdInthQ6bp6OHmXTIE8DKZbqpiBcUwNa6RxYtQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-31T17:35:51Z"
    mac: ENC[AES256_GCM,data:zX3VWyG1apXJeX9bopuyaIWuuisw2ZewC0nOJCUWOBKpYtF0GMLlIJXuEuMwxa3MJD1qhGACKTPBP5V7MP/O19aHgWGKqz6J17YdV1/o1M1IoABBnn/UpzyleR+p7Q+Dx26HGp72c+vx4O7xo34EXtM76Vza3nYHcx/EUmSgxtc=,iv:33Gub/z7SHw43iihpvvq9yLyDz6Npajvitls7Bzkl4s=,tag:bMat8tVX5EQnKtOMiXV+Fg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
---
kind: Secret
apiVersion: v1
metadata:
    name: forgejo-db-secret
type: Opaque
stringData:
    db-username: ENC[AES256_GCM,data:1iB28FTlew==,iv:JCwIpNZ46S0SINs7ramB8tOaulWsEEXEVEDQT5CYhEk=,tag:og9lUdJUsPOr1BphVMRlsQ==,type:str]
    db-password: ENC[AES256_GCM,data:C9rQrbO/LsCxMz3Chi4iOWjB+AeGnj5uwqyxCKildAo=,iv:hMSVlSWarSob3T8NbeS/oZyEd7/OPdQao0ZvYj/Y1Vg=,tag:BWxzbN7+StxG/tdtlmVJMw==,type:str]
    db-init-sql: ENC[AES256_GCM,data:IzYkbXAJw2aYo9SbFdpUSackIXt2RS2sWoFnHlMyx0cgkZmP8tn7L5Oe+1WZoaxlzjSEQR5QHwYZNU4SKcSNWwouH3qOtlziQec9wT6YIuUBHfqTtYYcPKZsqX334tx1lrwM7OtxnOvjY4Z7MpIVugevCiYkNJ9mYYQAhs3sFBRuhDtZpRsY6ib+6h4NSGsldRfHu/FHKN3x6XhJQPlHXipP6n+mB3zSwd6k/A==,iv:pxGeSW8nClJLTsTTobI/aQlteW+fc9rUhnNRTKJBQ4I=,tag:2aWNWiaIpawiW8RB9mO0JQ==,type:str]
sops:
    age:
        - recipient: age13ttsf4ee2xr4e90ydsrj9hk2gpjk9hktmxam0r08zeny75dwlc7qxap6zk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4TWt1WjR0NFJEdHNsNHl1
            Tzc2S2ozdEZsazd6eEtpTlpqajd6SzFJdkVvCmx0RVNFVnd2OE55Z2tUMzByeUJS
            STR3VHhtVmNlYUxYMXlWMm84YmdPU2MKLS0tIFhuTGM5UHZqUW9DaENHcXpRdlN6
            TmxWREVPVFhzMWI4QXdpcUlpL3l6c2MKysVHArMBoq2jl17P77bCFFJfhWWKEvrT
            ZZqBMUoi++CHhtFLkdInthQ6bp6OHmXTIE8DKZbqpiBcUwNa6RxYtQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-31T17:35:51Z"
    mac: ENC[AES256_GCM,data:zX3VWyG1apXJeX9bopuyaIWuuisw2ZewC0nOJCUWOBKpYtF0GMLlIJXuEuMwxa3MJD1qhGACKTPBP5V7MP/O19aHgWGKqz6J17YdV1/o1M1IoABBnn/UpzyleR+p7Q+Dx26HGp72c+vx4O7xo34EXtM76Vza3nYHcx/EUmSgxtc=,iv:33Gub/z7SHw43iihpvvq9yLyDz6Npajvitls7Bzkl4s=,tag:bMat8tVX5EQnKtOMiXV+Fg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
