apiVersion: v1
kind: Secret
metadata:
    name: forgejo-admin-secret
stringData:
    username: ENC[AES256_GCM,data:pI8zrRtA,iv:4lomRD9ti/NmjRlSGClL8PuUsuiJOxYGcpfn4lFtHjU=,tag:D/LTMyC4bVE+r+MYih4wPg==,type:str]
    password: ENC[AES256_GCM,data:BgfrxDggkyZCRw==,iv:v1pIX0TYrNx/Bm5cbizljhuKyoWfYLvh9Ni3W+NMC8s=,tag:t+V+PRf4Su20L0eQF3p/wg==,type:str]
sops:
    age:
        - recipient: age13ttsf4ee2xr4e90ydsrj9hk2gpjk9hktmxam0r08zeny75dwlc7qxap6zk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4TWt1WjR0NFJEdHNsNHl1
            Tzc2S2ozdEZsazd6eEtpTlpqajd6SzFJdkVvCmx0RVNFVnd2OE55Z2tUMzByeUJS
            STR3VHhtVmNlYUxYMXlWMm84YmdPU2MKLS0tIFhuTGM5UHZqUW9DaENHcXpRdlN6
            TmxWREVPVFhzMWI4QXdpcUlpL3l6c2MKysVHArMBoq2jl17P77bCFFJfhWWKEvrT
            ZZqBMUoi++CHhtFLkdInthQ6bp6OHmXTIE8DKZbqpiBcUwNa6RxYtQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-16T21:49:28Z"
    mac: ENC[AES256_GCM,data:GZo/5SA4PqF0QeHv66UepjTbJXA7TInIjy9cFA7kHmkzZBZlrBBan8i/w+nQHEDmTt1JSIGni/kbbnzz6kLujSh4tMvufH79gfDarJT0lYxqe8ZK4/yeN3DiFre4mdxgPa2ezeHmLPobTfH+r3e7n6l9Rectp1ieGTrUKptTW+E=,iv:19h9fajS3R1YeFEJPjl1nufqgSFA52QKiGzLEkljcEo=,tag:uM2XogmWD5Wya7Dol4xhkw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: forgejo-config-secret
    annotations:
        # This is required if you have $ in secret values to prevent kustomize from substituting them
        kustomize.toolkit.fluxcd.io/substitute: disabled
type: Opaque
stringData:
    database: ENC[AES256_GCM,data:M74FVDj9hS14dW65QWG3N/DBIrHjuskJwGuEy+LOgnaX61aPPf0RL+neCxUyVTzKvWNnOS4=,iv:9TJFuU+fbu/eOXGlOSLd6jIJqYFHch/oOhP/w7TESZQ=,tag:w0hYMO1NySLt+wqnnRa67w==,type:str]
    queue: ENC[AES256_GCM,data:neG3l7pY0kdzVKYOnd7ZMk7i7kBVEq6NHlxj++J+ua09DsdET46NdRqsB6XhsINg1/dQ6BjCSczqyPqNnb1TX4Q=,iv:FNBjEmfheszPcs3MhG+aOpjsyhmsh8wt249DqcH2Ejo=,tag:Bg0CMKHwPf8EemN0jighzg==,type:str]
    cache: ENC[AES256_GCM,data:iQrZlKPOYM4Owql4n3xTEhle26tQndx6Z0FqNGlfBNFazjyR0nL1TR/oImNvzohtWb8vTIiIJfFWyuPyyE7qMu7kVXIIuTD/toDfGIrPCzNUitJIJZmO6mNfza+PxiDQ,iv:0g1H1he8CvcyzcYj68OIQKpq38Y6NDJqLj1Y8GR+9ac=,tag:i/R+gisBulgYUFXBWode3g==,type:str]
sops:
    age:
        - recipient: age13ttsf4ee2xr4e90ydsrj9hk2gpjk9hktmxam0r08zeny75dwlc7qxap6zk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4TWt1WjR0NFJEdHNsNHl1
            Tzc2S2ozdEZsazd6eEtpTlpqajd6SzFJdkVvCmx0RVNFVnd2OE55Z2tUMzByeUJS
            STR3VHhtVmNlYUxYMXlWMm84YmdPU2MKLS0tIFhuTGM5UHZqUW9DaENHcXpRdlN6
            TmxWREVPVFhzMWI4QXdpcUlpL3l6c2MKysVHArMBoq2jl17P77bCFFJfhWWKEvrT
            ZZqBMUoi++CHhtFLkdInthQ6bp6OHmXTIE8DKZbqpiBcUwNa6RxYtQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-16T21:49:28Z"
    mac: ENC[AES256_GCM,data:GZo/5SA4PqF0QeHv66UepjTbJXA7TInIjy9cFA7kHmkzZBZlrBBan8i/w+nQHEDmTt1JSIGni/kbbnzz6kLujSh4tMvufH79gfDarJT0lYxqe8ZK4/yeN3DiFre4mdxgPa2ezeHmLPobTfH+r3e7n6l9Rectp1ieGTrUKptTW+E=,iv:19h9fajS3R1YeFEJPjl1nufqgSFA52QKiGzLEkljcEo=,tag:uM2XogmWD5Wya7Dol4xhkw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: forgejo-runner-secret
    namespace: default
type: Opaque
data:
    #ENC[AES256_GCM,data:+06SF7aBiVy+zoksJMYs77xxEzM/kHo6uShcodyjPb1lvyLsoGs7E+PiKTBXZ/v2cHYtSzr2d3/Pwkhk9t6uRFP5IsduIogtiH2Qg/I=,iv:V2Sgle5Vu+u+i5OTzLJpxaJIK0CcdQ5dvKtZipq7+5E=,tag:sMyzs0aHpEVh8JUUP2LhHw==,type:comment]
    #ENC[AES256_GCM,data:Eapw572b8L3MZWtWBG6ALvot887UK6uuQKbnQaDd20xfrjJyXs48GpEvkMCYbr+WMkMJtf9J2L7nb8F8VIgTBv8ZR8jkLEaE7+MSBbbU9NNWgwWuOnvSyoMnnxw=,iv:xcjVKdMOFbqcfVSRNF3ngw4YgfUYhL/SOI7v0er6RHE=,tag:XEBbYDH96J/VdGteys41yA==,type:comment]
    #ENC[AES256_GCM,data:kZvZWkibexCOdzfEmwl9yRLu0la28k7Vj8zeGYosQxALNmwwn5aCUhR8LjzVmNNlM5cnmYZLDPU6mQwK0/gEGeHdBikAbGO6nO5PSwRKV7opYUMlCACf53q1zdondHA=,iv:c1vWmthXANbege4EYrfUCqq2rgtyHzLr4v0S8fZeQ20=,tag:IxzIF2RtrdLFsxammJ8sUw==,type:comment]
    token: ENC[AES256_GCM,data:8qsPoPUKHKOlRc7grFNv4deDYVuFrTi5uCPA/B/pjyVNZFT9zPmcj/eq/uGoUSGmkMqXoy+Bwm0=,iv:xzc610m/99Ds1QHFNN71bHkdt0vXvAydWsAAgMCVvBM=,tag:Gkogr1/WqSTHCcZ7IEY9+w==,type:str]
sops:
    age:
        - recipient: age13ttsf4ee2xr4e90ydsrj9hk2gpjk9hktmxam0r08zeny75dwlc7qxap6zk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4TWt1WjR0NFJEdHNsNHl1
            Tzc2S2ozdEZsazd6eEtpTlpqajd6SzFJdkVvCmx0RVNFVnd2OE55Z2tUMzByeUJS
            STR3VHhtVmNlYUxYMXlWMm84YmdPU2MKLS0tIFhuTGM5UHZqUW9DaENHcXpRdlN6
            TmxWREVPVFhzMWI4QXdpcUlpL3l6c2MKysVHArMBoq2jl17P77bCFFJfhWWKEvrT
            ZZqBMUoi++CHhtFLkdInthQ6bp6OHmXTIE8DKZbqpiBcUwNa6RxYtQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-16T21:49:28Z"
    mac: ENC[AES256_GCM,data:GZo/5SA4PqF0QeHv66UepjTbJXA7TInIjy9cFA7kHmkzZBZlrBBan8i/w+nQHEDmTt1JSIGni/kbbnzz6kLujSh4tMvufH79gfDarJT0lYxqe8ZK4/yeN3DiFre4mdxgPa2ezeHmLPobTfH+r3e7n6l9Rectp1ieGTrUKptTW+E=,iv:19h9fajS3R1YeFEJPjl1nufqgSFA52QKiGzLEkljcEo=,tag:uM2XogmWD5Wya7Dol4xhkw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
