apiVersion: v1
kind: Secret
metadata:
    name: forgejo-admin-secret
stringData:
    username: ENC[AES256_GCM,data:/BdYyYRPed7hkrqK134=,iv:kKwpp77BzjtK9w+wi4ko8n/ZKGyY98KT3QLd21QJOOE=,tag:Yb5CdA0tE84FSJkWWEAUqQ==,type:str]
    password: ENC[AES256_GCM,data:BgfrxDggkyZCRw==,iv:v1pIX0TYrNx/Bm5cbizljhuKyoWfYLvh9Ni3W+NMC8s=,tag:t+V+PRf4Su20L0eQF3p/wg==,type:str]
sops:
    age:
        - recipient: age13ttsf4ee2xr4e90ydsrj9hk2gpjk9hktmxam0r08zeny75dwlc7qxap6zk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4TWt1WjR0NFJEdHNsNHl1
            Tzc2S2ozdEZsazd6eEtpTlpqajd6SzFJdkVvCmx0RVNFVnd2OE55Z2tUMzByeUJS
            STR3VHhtVmNlYUxYMXlWMm84YmdPU2MKLS0tIFhuTGM5UHZqUW9DaENHcXpRdlN6
            TmxWREVPVFhzMWI4QXdpcUlpL3l6c2MKysVHArMBoq2jl17P77bCFFJfhWWKEvrT
            ZZqBMUoi++CHhtFLkdInthQ6bp6OHmXTIE8DKZbqpiBcUwNa6RxYtQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-31T15:44:42Z"
    mac: ENC[AES256_GCM,data:7KJBwqFpR9MDXMemBLhWliLA8yJiuYPiZ9jozZomU0Gz4zYtCLzlboWtaxqmXf6efhr2Gx8TmWajXfRofeuTSIFdKNgVxspIaW4xz/XTUKKE9/IGGuSXOFfOf8hhVXR1jdS457MmOI2GGXGsfE2+cLYgl6QOytF8bk5F4TLEYI0=,iv:AWJ967VZTMMdNxGNiV0flN+tVnm4UNJ81sjiCTVcDXo=,tag:E6nKt542FGjRFJf8Ooz6Hw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: forgejo-config-secret
    annotations:
        # This is required if you have $ in secret values to prevent kustomize from substituting them
        kustomize.toolkit.fluxcd.io/substitute: disabled
type: Opaque
stringData:
    database: ENC[AES256_GCM,data:HoT69tm/vHQ88e7HmnNNiwLsn1lWnLHrornpAAOQsfI4r3RbwsRnZaRw2nlafWph9RF6wL7A05/9mExu/+RbFDcD,iv:cfZO4Xk7qe17H35zmfQz7zT+cVmq/fliUTyaZoYpm3o=,tag:+Bc+jOya1rCfl/yB810SJw==,type:str]
    queue: ENC[AES256_GCM,data:neG3l7pY0kdzVKYOnd7ZMk7i7kBVEq6NHlxj++J+ua09DsdET46NdRqsB6XhsINg1/dQ6BjCSczqyPqNnb1TX4Q=,iv:FNBjEmfheszPcs3MhG+aOpjsyhmsh8wt249DqcH2Ejo=,tag:Bg0CMKHwPf8EemN0jighzg==,type:str]
    cache: ENC[AES256_GCM,data:iQrZlKPOYM4Owql4n3xTEhle26tQndx6Z0FqNGlfBNFazjyR0nL1TR/oImNvzohtWb8vTIiIJfFWyuPyyE7qMu7kVXIIuTD/toDfGIrPCzNUitJIJZmO6mNfza+PxiDQ,iv:0g1H1he8CvcyzcYj68OIQKpq38Y6NDJqLj1Y8GR+9ac=,tag:i/R+gisBulgYUFXBWode3g==,type:str]
sops:
    age:
        - recipient: age13ttsf4ee2xr4e90ydsrj9hk2gpjk9hktmxam0r08zeny75dwlc7qxap6zk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4TWt1WjR0NFJEdHNsNHl1
            Tzc2S2ozdEZsazd6eEtpTlpqajd6SzFJdkVvCmx0RVNFVnd2OE55Z2tUMzByeUJS
            STR3VHhtVmNlYUxYMXlWMm84YmdPU2MKLS0tIFhuTGM5UHZqUW9DaENHcXpRdlN6
            TmxWREVPVFhzMWI4QXdpcUlpL3l6c2MKysVHArMBoq2jl17P77bCFFJfhWWKEvrT
            ZZqBMUoi++CHhtFLkdInthQ6bp6OHmXTIE8DKZbqpiBcUwNa6RxYtQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-31T15:44:42Z"
    mac: ENC[AES256_GCM,data:7KJBwqFpR9MDXMemBLhWliLA8yJiuYPiZ9jozZomU0Gz4zYtCLzlboWtaxqmXf6efhr2Gx8TmWajXfRofeuTSIFdKNgVxspIaW4xz/XTUKKE9/IGGuSXOFfOf8hhVXR1jdS457MmOI2GGXGsfE2+cLYgl6QOytF8bk5F4TLEYI0=,iv:AWJ967VZTMMdNxGNiV0flN+tVnm4UNJ81sjiCTVcDXo=,tag:E6nKt542FGjRFJf8Ooz6Hw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
---
kind: Secret
apiVersion: v1
metadata:
    name: forgejo-db-secret
type: Opaque
stringData:
    db-username: ENC[AES256_GCM,data:1iB28FTlew==,iv:JCwIpNZ46S0SINs7ramB8tOaulWsEEXEVEDQT5CYhEk=,tag:og9lUdJUsPOr1BphVMRlsQ==,type:str]
    db-password: ENC[AES256_GCM,data:C9rQrbO/LsCxMz3Chi4iOWjB+AeGnj5uwqyxCKildAo=,iv:hMSVlSWarSob3T8NbeS/oZyEd7/OPdQao0ZvYj/Y1Vg=,tag:BWxzbN7+StxG/tdtlmVJMw==,type:str]
    db-init-sql: ENC[AES256_GCM,data:IzYkbXAJw2aYo9SbFdpUSackIXt2RS2sWoFnHlMyx0cgkZmP8tn7L5Oe+1WZoaxlzjSEQR5QHwYZNU4SKcSNWwouH3qOtlziQec9wT6YIuUBHfqTtYYcPKZsqX334tx1lrwM7OtxnOvjY4Z7MpIVugevCiYkNJ9mYYQAhs3sFBRuhDtZpRsY6ib+6h4NSGsldRfHu/FHKN3x6XhJQPlHXipP6n+mB3zSwd6k/A==,iv:pxGeSW8nClJLTsTTobI/aQlteW+fc9rUhnNRTKJBQ4I=,tag:2aWNWiaIpawiW8RB9mO0JQ==,type:str]
sops:
    age:
        - recipient: age13ttsf4ee2xr4e90ydsrj9hk2gpjk9hktmxam0r08zeny75dwlc7qxap6zk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4TWt1WjR0NFJEdHNsNHl1
            Tzc2S2ozdEZsazd6eEtpTlpqajd6SzFJdkVvCmx0RVNFVnd2OE55Z2tUMzByeUJS
            STR3VHhtVmNlYUxYMXlWMm84YmdPU2MKLS0tIFhuTGM5UHZqUW9DaENHcXpRdlN6
            TmxWREVPVFhzMWI4QXdpcUlpL3l6c2MKysVHArMBoq2jl17P77bCFFJfhWWKEvrT
            ZZqBMUoi++CHhtFLkdInthQ6bp6OHmXTIE8DKZbqpiBcUwNa6RxYtQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-31T15:44:42Z"
    mac: ENC[AES256_GCM,data:7KJBwqFpR9MDXMemBLhWliLA8yJiuYPiZ9jozZomU0Gz4zYtCLzlboWtaxqmXf6efhr2Gx8TmWajXfRofeuTSIFdKNgVxspIaW4xz/XTUKKE9/IGGuSXOFfOf8hhVXR1jdS457MmOI2GGXGsfE2+cLYgl6QOytF8bk5F4TLEYI0=,iv:AWJ967VZTMMdNxGNiV0flN+tVnm4UNJ81sjiCTVcDXo=,tag:E6nKt542FGjRFJf8Ooz6Hw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
