apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:6giCWVNsplt+GWX+ZiwidTVq5vF3kbY4mCQufFKyEzikHCFmt0FBwM5aB+DcSU4DiG0eLswY788GKr/oeZforCWy/k01OZFFFmtHiX5/ue6HKI8hj0N/amGeFIubvcB8LCuIw1scCrKa0WtODMTTkNMSE5274a5lET6gYVNtvILthHcVqjsurg/HeesvDIA3mH3sp3YWFi7U1ba21KiYbQV0x1MSQmn/d7Jng6rlWcTAitI0,iv:86X32uEXu7rgx/LTcftuq19SWaDGHEjqP48QRNhpYQ8=,tag:P4SHjWehsvzp+k7s2WP3fA==,type:str]
sops:
  age:
    - recipient: age13ttsf4ee2xr4e90ydsrj9hk2gpjk9hktmxam0r08zeny75dwlc7qxap6zk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoSzNxTFBwcFNhRmFoUXZS
        TkFuZEpvN0lXT040R3M3dVJYZWtudXJZaEM4Cmp6ZitwRERHOE4xMks4RHVlVVBY
        RkNjN0ZVRkNxNXpiKzRseUJkeUNVdGMKLS0tIERZNkpONVUzWWJCamp3NDNWRHNQ
        TnFzT1dpclg3RVZ2clltams4bHk2azAKREng3P3QA8on23Y2v4+3l6gG12k9JNBV
        QLMdmOJ0SGkCZ0TU0X7naFoBpr5fZXgT1vDkiolYl09csm7Q/RSk3A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-06T22:47:37Z"
  mac: ENC[AES256_GCM,data:tZPnr4eg7jQPvpn8kvLFAH+x5zmBnoBe8osIoeOLF6lW3OOIUXgGpgj7Dvid5PNAUjX+YDqn87IMbMIzl3m4TVHRqQ2J3LCZr13MPHd3DFc+PhSMGHSQbjrir+yRsKcWmP1F0PdV559XVZoLt7q6K4jYh+fYTD9rFYPukYprDBw=,iv:w96BqBoAkPgYnCqzslzYzDq3Vu3MtZvB/B5V6UeaCP4=,tag:s9QV0dZ8nfXhbnHu5dR91A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
