apiVersion: v1
kind: Secret
metadata:
  name: universal-auth-credentials
type: Opaque
stringData:
  clientId: ENC[AES256_GCM,data:CP9MCjcz/oUY032Qttnb6bj0WqPOlQO1+HZYY4hj3Ue94U5m,iv:ZvyKSO4SInQLahPOwWWOEA19tsjHoHk0MSqQRgyiWNE=,tag:V0zMh04nxgi6hhR6sx6Cqg==,type:str]
  clientSecret: ENC[AES256_GCM,data:U45lE8HjTDuRmiK0wqB6WGl6gcvql7w8VN2D+yWfSrYpBrW233sL+tlbQVdbPKtI4B839AswPuVHKnu9LR4ljg==,iv:OiKDVCNxKlJzqm5uLxFfepsRiGC0FVKA+3x4OjdFqrI=,tag:hkZ5UIoxTkqUgCU71fSGqw==,type:str]
sops:
  age:
    - recipient: age13ttsf4ee2xr4e90ydsrj9hk2gpjk9hktmxam0r08zeny75dwlc7qxap6zk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHaThieVdVMmRwNEJHaWZ0
        WHl6cDF2RUdTWkdpbVEvYkJFcHdmWkJYQTFNCk9jZXFLT3NFdHhnZHNjYndkR05T
        SGxSSHJ6L1VPMWFQM1pWTkJjWUZjM3MKLS0tIElweFd1b2tsVGczejQrK0FMbm01
        OFd1RmRnV1AxVGhyanVQeG02Tys4NVUKK6vLR4q7O28t1GCvTh1vP06e8+/2/iL5
        UVvVmCFLxQIlqB+yz/yi7tmEXa/JPrqSf878v8ED3hR/AUvtgL2OVw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-16T23:51:54Z"
  mac: ENC[AES256_GCM,data:7FB254B5Q27QgDWM8zlab743cBsknF/MYOPyY3keTigX7gtMD2bGUC61xEUWfmpknm51AKRK+bw4M5+48tjiHZVM8FhG4Pvr9FvI5sirizukIJxQcTTr2l39USFaUk1of6QUY4JradjUhXi/PcvztmIIWdxlnOvYoqC0+ILKnzM=,iv:ZlkoRgG1ZSCIItqq45+z2gRZA1LrsXqQJ1qLw864Dn8=,tag:xEJuHLanLQxfoWxaYUGw0g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
