apiVersion: v1
kind: Secret
metadata:
  name: runner-secret
  namespace: default
type: Opaque
stringData:
  #ENC[AES256_GCM,data:IAYa6lq8nwvLHR6daQrBpYZR1olVzt6ujC5Ux3pBvdJch+b2BgmLFTA+TYlsW66yRK9s2zWRKlYyiSorVJa4cC7yEFSYtx0XzKMnMiQ=,iv:uMwu31XtsRqcSvZYulKavFAlb3PZAaecFPTPsRap38M=,tag:jZLZwpaNbQEixB2wsISE4g==,type:comment]
  #ENC[AES256_GCM,data:JtSf9iJYDirka+DBKaHpKMZHzrVh5hbv2Zq5sNSC/7J1Q4oRG/uR3jjSrVwrpl+cPPzthTStR7HewaQpff6gzoKfjHzLEoyUjj0Oo5Tz0xT/R7r2TMKIiERHiYw=,iv:tWJffjYde9/HvFSMomKQCvKOe1usiWLqGtbA7UR27LI=,tag:9VuHiwM4MWdIpD87G7iqbw==,type:comment]
  #ENC[AES256_GCM,data:N1hjq/t1tvpPgGxQyvDcMSx9RhaDnK5xIfIhDkwqjaSN+KWymLPu6LsBLueDbr10k2tyeLSZI/yGoUPG2AT76k5zldEZlwwRw5LTQcmxu4MpfXJzqBkB27uAJGtHXKk=,iv:T9gacxuLHjALtalPryTAFlJ1Tfnw3BAC+zjaUAr5uUo=,tag:UgXO9jFIhFYZq/Bknd6Lqg==,type:comment]
  token: ENC[AES256_GCM,data:B23FhkhPmqrk4ELAvdHJZDtmW90VBXZT7nZrnsbx0TyReX4ryq/FFw==,iv:qjfVkyM9jFsNxxJNg89hXOheMLaxt/DWXAGrjqQz//k=,tag:Ha8U5nleY+PSLlhRA+6Mpw==,type:str]
sops:
  age:
    - recipient: age13ttsf4ee2xr4e90ydsrj9hk2gpjk9hktmxam0r08zeny75dwlc7qxap6zk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Zkt1SE9vcG14OXZjaFNa
        aHVyNkFmNlNQekMxNEo1SU9tL05ydXBScHpNCjI0OVBKR0xYZFRUTlpRR0h6dnJH
        UzY5QUw5OW1RZGpEYkZydVY3WmpUZmcKLS0tIHliOVBCNlIzVjJKVHVzOU1VNUla
        TGJzQzhDSnBMc3VCaVpFSnZYYlIyckEK1yrzOGUeiZyt07KvoADuE4ifOzGWsNHV
        Hfz7Z+4b59Bd400NvdrOjKJRRG24aE91I8PxthZC0WGsIZ+3bMFEYg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-09T04:23:21Z"
  mac: ENC[AES256_GCM,data:fRVcSP/6l4iITE/s0bRqNypmmbFOzT+oMT2mIiRm8YIhWm+I6erDCsmhWngOEECA+NKb0+hg8OKBUSyGjVaVRbWf0dnfUBMYN8rudKQUolWaFzeDCebOOxfx7o4QdutqBLV70/36yracuh092XO7FKF3HzyLIpPTNK7KsoaW+t0=,iv:AMwkIroWB7NrQGRlmoFt01/gVjRCMCmEeyq1hRf+MSQ=,tag:5gRPlok383heGxOtF6P7wg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
