apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: radarr-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword

  target:
    name: radarr-secret

  data:
    - secretKey: RADARR__AUTH__APIKEY
      remoteRef:
        key: radarr-secret/RADARR__AUTH__APIKEY
