# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: radarr-secret
stringData:
  RADARR__AUTH__APIKEY: ENC[AES256_GCM,data:8T99Kla5KSzwQFjfW78e0dQKxkwO4dbB,iv:WHcRqeeCrlvXbfeyT9O0eFyGBDwNKZYQ7qBgAkRAaxU=,tag:jpMZTJCcvQvqQSwYcAjy2Q==,type:str]
sops:
  age:
    - recipient: age13ttsf4ee2xr4e90ydsrj9hk2gpjk9hktmxam0r08zeny75dwlc7qxap6zk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4SUxmVTNjNjVxOE1hbVNW
        ZS9pTkJpc21kQmJmSU80WFEyZmRzYnExK2k4CmVTVGlKZXlpL0s3aTN4Uk9Ddm1v
        QzRqK1VWUjhIODMyTFhEYVZLNm5VNzQKLS0tIFlpWitnRjRKaC9mWnRrSGM3Z2p2
        eEpVU2xJK3FIei8rODdwaUViQmJqb2cKZcy+pTUmEnYMfHTHsRyXXDC633yHYesp
        gRHr+eQIdFI/NNs7ikXA+6hfFp/EfodEENA+38TwmNnahVgJZgN1Gw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-09T04:23:21Z"
  mac: ENC[AES256_GCM,data:mj+Vf9/FLoyXhwheD4/Uc9svftR43dFEndAh9GcqtvnKVzJvuizBfHQKkCtLNULo7QggBrChSjT0lgA2O7Sew5+/62Ej7DMgahseFNemWxlwucnPEdy4tTUjHkkzbTiiiSFRAm0Hpl8iY2j6LTsJ+o95dZ2+TsVl/wcJsa/1hxQ=,iv:34LAr00wnOB5wW8j40AxF9Ilnhb6GA9+KYgGRdIE+rM=,tag:WplkwEPQ5vftRkyiPjN67g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
