apiVersion: v1
kind: Secret
metadata:
  name: capacitor-next
stringData:
  LICENSE_KEY: ENC[AES256_GCM,data:2c0422ondgE+RFjS9wWXUmYp0vcwUqShqh+QYQ+4LktIkY7JI/ida/NMSVI3DRdGSuRlFm91ODUAI5/p0/pDL/DuUmwg8qG5D/U+XrL/zzwyT9HOcfe8b78RelNKdc+nUBhko9jxWsjbxK3vf7K9B133tHoD4iTR5ZYz/7QVcvff3MHH4xPadkzhJpE/kFF23yrwbemoOfp34iPJyYOmC+kJbcgBBnsNSqqxKbwOa+0TMwOv9JxwoLPGzA==,iv:F9LOXQdzWXcoxHh0AzW4gZwS/DxJmnjExIooHf9Yttc=,tag:xVWIjoDYhWBGbnS5OhS3aA==,type:str]
  SESSION_HASH_KEY: ENC[AES256_GCM,data:PN92uQwo4iEoInEMl/HyUynJM/uUI/MWVDzfx4untqiOmFMt8mZzLT+7PxasO2HJWiCC,iv:ZOGUCwVXvVg2ZSTvYUNQa/mokkUnJPlQqCdwL2e6vlg=,tag:AKFnWf6HHeTLqlXHPJIYwg==,type:str]
  SESSION_BLOCK_KEY: ENC[AES256_GCM,data:1x5A8v1vE/Whd/nRWEuSke+c1vUwaccjtXkI0/r8Mva9ZX5fK27Y6NgXZJz48B0GiomN,iv:K6ud9SvXZq9VGweyhUe9nmzc15B3Qj4XbFAgJe10wLw=,tag:6IbW3wwPZfp9obTWmZUKqA==,type:str]
  registry.yaml: ENC[AES256_GCM,data:gHmSmmsjEPrTJ8N3gPx6WL2CdFPz9aNgscS3qvhBpnL8wil2XW8r1Thtw7zoYM0N2ufcChM8KISKPlMToxEek0hEw20nAyC7YS8IxHZUOHNfwilwAhWa9ZegJ142EdUJvrePHhnCh1UyhLLhpElg9N3bZ/1gXI98Rlni2wcwbsOIirqZqBfsnVySlV8rwkAvkwcB+uVxI2FjJPQ53hUeN0RHE9FJWwIMgT8IeEzZ73zrnBKFDyknyxZ+u0wZVd8LatbY/UrYLqbdNf4/04xEd44RGoww1Sh/gcurAVwFSr90ivgwBejI1pvGYllIrhU8fjCSN4HX+mC1PAHme9meq7zOrQ==,iv:pIuVeE92+HxXFOLhjf2FF5Z4iWWGCleMgzcEBw5kLzs=,tag:h3ftoyugM2fHvTkSttCQaw==,type:str]
sops:
  age:
    - recipient: age13ttsf4ee2xr4e90ydsrj9hk2gpjk9hktmxam0r08zeny75dwlc7qxap6zk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDdE52YVF5eW9UYlhuZVEw
        S0IrZHFDK2xmUkszMmpSUnBCN3Q1cnpsTXpFCnFUMVhaYS9qeTAxclhRWnB3bE93
        NzhreCt2T29mdSt1UkREV040a0NCaFUKLS0tIHNoR1BPZUR2NEFDUzJzR3c5aHN5
        aTBYRnNjVnlZUE4xdWpQUkg5NDYxaFEKJfutGiuMMras9tnzIryQXYjKB+gnn+4A
        +nKtF6Hb67CUuBmsBkAxGhHzlBOeuk+qRa2a8G2xXy1Squ6Zm74YPg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-01T02:37:44Z"
  mac: ENC[AES256_GCM,data:ZWwVODkhLCL8AvQ9n+muJR9UGsoX5VVLcZdf85PGlrOzNYF4S8mncyIkSbJ8g4H1BbRdgqt3NW4LGoIeJZhDk8hmmmKUU/19KAY42SKJnNuiK6612y4qha5tGeiKghvGLn1EtaRU7vMbLmu4jSHswLP/EUy/q44ac9N+QvJbWYM=,iv:YXppkXSNtzuJBzRfY9E9thcMZjXXpC5vEOfsW4AoABk=,tag:Qp+BWiKCrOD3I6iNu/4pDA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
