---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nebula-sync-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword

  target:
    name: nebula-sync-secret

  data:
    - secretKey: PRIMARY
      remoteRef:
        key: nebula-sync-secret/PRIMARY
    - secretKey: REPLICAS
      remoteRef:
        key: nebula-sync-secret/REPLICAS
