apiVersion: v1
kind: Secret
metadata:
  name: nebula-sync-secret
stringData:
  PRIMARY: ENC[AES256_GCM,data:fk+gepc5Ol90kEMuD4x5dSjYKxhyujhlpav8eQ==,iv:tY74XWAmbF6hWHt6v0FAPZy0B88WO9nEtGm2SqLYBMc=,tag:0i+yg6SlGccJSdaCx9WR/A==,type:str]
  REPLICAS: ENC[AES256_GCM,data:P+YaiJ4EiytZtUi5pZ7MVnVaD5uSLLMvm2PPGA==,iv:mStFfbR9wg7z+6Jcdx8aSY3qbVb9cU9MTt+YFMmMwDE=,tag:BmGHZRyfB7C5TS+72cpdRg==,type:str]
sops:
  age:
    - recipient: age13ttsf4ee2xr4e90ydsrj9hk2gpjk9hktmxam0r08zeny75dwlc7qxap6zk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZaHdFMFJVaVFlWXNnWlVy
        UzRVQ1BQMUF1ZGR1V2Njdys4Q3Z5NEtTUURNCmZFQnBaY2tGNXN5RXVNejVZOFUz
        RlYwa0Q5NDNCQVNVTjllMUc5TlB3eG8KLS0tIHhhbnRmckcwZTFNWSt1dHdFVGZx
        c1VreHNkdGgzdVBiNkcrNi9tRzloU28Kzpy6N5zUzZZvTGCcE6SalHAaEpquZCj8
        M4ToJpmddia8fZYV7gGxPcO2OciuMZKQud2BYmj5GDqpGCXtrhkMKA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-12T00:02:22Z"
  mac: ENC[AES256_GCM,data:ktwS5i1n7FuUbGZztKR8win24l9cGSzQ3HU5QNZq1q4MMcZyp/aEFyoOOzFrYlktEWhNGw7nRusktbY0Dskk2HXit9cykmsLX+mYPX9cJN9Mvn7n2dXske2RtfbyMFd8spAeBl+DfZKti8JPwzJcirnfIj5BxHKZNYD2ZiZvMpg=,iv:xZ5GP7n2cx7fikYXv/ukyYogelZ3k/wuLP0Dc4nfQYs=,tag:5wOG2H2GM5T4u/evxKhcyA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
