apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: manyfold-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical

  target:
    name: manyfold-secrets

  data:
    - secretKey: DATABASE_PASSWORD
      remoteRef:
        key: /databases/MANYFOLD_DATABASE_PASSWORD
    - secretKey: DATABASE_USER
      remoteRef:
        key: /databases/MANYFOLD_DATABASE_USERNAME
    - secretKey: SECRET_KEY_BASE
      remoteRef:
        key: /apps/MANYFOLD_SECRET_KEY_BASE