---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: manyfold-pvc
  namespace: 3dchi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi
  storageClassName: ceph-block