apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pihole-dns-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword

  target:
    name: pihole-dns-secret

  data:
    - secretKey: api-token
      remoteRef:
        key: pihole-dns-secret/api-token
