---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app pihole-dns
spec:
  chartRef:
    kind: OCIRepository
    name: pihole-dns
  interval: 1h
  values:
    fullnameOverride: *app
    provider: pihole
    env:
      - name: EXTERNAL_DNS_PIHOLE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: &secret pihole-dns-secret
            key: api-token
    extraArgs:
      - --pihole-server=http://10.10.10.6 # Primary Pi-hole, do not use the VIP here
      - --pihole-tls-skip-verify
    triggerLoopOnEvent: true
    policy: upsert-only
    registry: noop
    sources: ["crd", "gateway-httproute"]
    domainFilters: ["${SECRET_DOMAIN}"]
    serviceMonitor:
      enabled: true
    podAnnotations:
      secret.reloader.stakater.com/reload: *secret
