apiVersion: v1
kind: Secret
metadata:
    name: pihole-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:mMDMqU0zx46hOw==,iv:FDiVUyOuFlgyKoeU9xxo878jCLl5cViuVVWCs/yhuPA=,tag:hjACqDeqI1XDcM0M4f08vA==,type:str]
sops:
    age:
        - recipient: age13ttsf4ee2xr4e90ydsrj9hk2gpjk9hktmxam0r08zeny75dwlc7qxap6zk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcEpJckNRbCtSckZmN1Yz
            c2VadW1YVk9HN2M1VUt6NGlwS01NMmkrZUFzCkdkZHowL3MwZWhJUWVaTFZxWGoz
            TkpwcUV6VTBGSFpJQ2p6dlhVK05INzgKLS0tIGE4Sk02VGZPeE5Bd1BBMlJDWDJJ
            cERFU3E2My8yak11ZlFEWWg3MU1PR2sKAFfU3R8woeK81cbiKncZ/ZkD8YP53ZgV
            hb9jSbKLqYTPOzjWyy52Uf7wwp1Tk1maStsaVW52xhgD2X7Ul9TZDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-12T04:38:20Z"
    mac: ENC[AES256_GCM,data:qVcOmia/ZmbHKGbPaMriZZtjKAxk1Be0475YIcyro+8gI2XhDlbY4auZ+DDGB+tFnsgvw9qjuKcCg5FIT9lvFzEJluMMyEHcobELWw1bTjRxVfp1Pmhfuyy+UU4eMdrjxDDonzi3ZJtYo0hZwa7aGkub2KyoBhIC8Ih0TYEbNS0=,iv:1OSVojVsmrbP8eGJZFB/zsdVwu66vVkzQPra0eZ3lqw=,tag:rIhLD6zW5rqpMr8UUkbDiw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
