apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: infisical-managed-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical

  target:
    name: keycloak-db-secret

  data:
    - secretKey: db-password
      remoteRef:
        key: /databases/KEYCLOAK_DATABASE_PASSWORD
    - secretKey: db-username
      remoteRef:
        key: /databases/KEYCLOAK_DATABASE_USERNAME