apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-admin-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword

  target:
    name: keycloak-admin-secret

  data:
    - secretKey: admin-password
      remoteRef:
        key: keycloak-admin-secret/admin-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-db-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword

  target:
    name: keycloak-db-secret
    template:
      type: Opaque

  data:
    - secretKey: db-username
      remoteRef:
        key: keycloak-db-secret/db-username
    - secretKey: db-password
      remoteRef:
        key: keycloak-db-secret/db-password
    - secretKey: db-init-sql
      remoteRef:
        key: keycloak-db-secret/db-init-sql
