---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak
spec:
  chartRef:
    kind: OCIRepository
    name: keycloak
  interval: 1h
  values:
    keycloak:
      adminUser: admin
      existingSecret: keycloak-admin-secret

      httpEnabled: true
      httpPort: 8080

      hostname: auth.${SECRET_DOMAIN}
      production: true
      proxyHeaders: "xforwarded"
    
    global:
      imagePullSecrets:
        - name: forgejo-pull-secrets

    extraInitContainers:
      - name: custom-themes
        image: code.bihun.dev/bihun/keycloak-customizations:latest-rc
        imagePullPolicy: Always
        command:
          - sh
          - -c
          - |
            cp -r /themes/* /opt/keycloak/themes/
        volumeMounts:
          - name: keycloak-themes
            mountPath: /opt/keycloak/themes

    database:
      type: "postgres"
      host: "keycloak-db.default.svc.cluster.local"
      port: "5432"
      name: "keycloak"
      existingSecret: keycloak-db-secret

    metrics:
      enabled: false

    # Disable embedded databases
    postgres:
      enabled: false
    mariadb:
      enabled: false
    
    # Disable Ingress to use Router instead
    ingress:
      enabled: false
