apiVersion: v1
kind: Secret
metadata:
    name: keycloak-admin-secret
stringData:
    admin-password: ENC[AES256_GCM,data:RpO24nJ/tzQetQ==,iv:8TFspkldD6zKUn7JhiaITtcSFcTrMg4atC4z194lYAs=,tag:5++s+tZMqoj9s7mRe1/Mbw==,type:str]
sops:
    age:
        - recipient: age13ttsf4ee2xr4e90ydsrj9hk2gpjk9hktmxam0r08zeny75dwlc7qxap6zk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoVllkaHJ3RDRiNm0yN3NN
            T2RJRThNRGpaOUdwa2ZvWVRoQkY0VXZlZEN3CnJUWENQdXNMNXpseWdnSHI2bENH
            SVdLT3pqL2VZSmVwTlNqUHlZYlVjWEEKLS0tIGF1cGlpcEVHL1F5MTg5MEhQMWZt
            OEx4ZzErZm8xUDRoeERxSEJ3TzZ3Mk0KmiuF9ePFUTvxDLT8Yi6Pelb8vQB008Tu
            FklyJ6AQDjo5+WmTrn/YkAmJUWfql9BpHYAbP5ZzXHExeH7Z17hbWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-31T15:17:13Z"
    mac: ENC[AES256_GCM,data:lx8J5PIhC+b640A6wLQ1VRPqcoKprI4vN9iquD+ner3hdtWbcTEgtpAbAFhsQbTjx75BAwPdxr8eHHo5VNLnj2Iy6Yk236sl6tsKJYwg+pdiXi42ZK2jK6XYWCRiw/rElcsCTn74TXun73fwamLDXKL/+K6VeCFvUt1bT5dXvB4=,iv:57Se03PV77J6HEW0cZlpLwKCv1Dr9R9IUmoKIOkffNo=,tag:gcmFdwOn/el06YtsEEVhZA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
---
kind: Secret
apiVersion: v1
metadata:
    name: keycloak-db-secret
type: Opaque
stringData:
    db-username: ENC[AES256_GCM,data:BsLII0A5fT8=,iv:mJaG1QcTW/n4jIvLRzCFep9ATC/XD2k6xWgvitWQkSg=,tag:Fc1jLYxkUJDrL0FjpqdtNA==,type:str]
    db-password: ENC[AES256_GCM,data:98Hjqvcsz6WX6Vv4gLQzO25ReB3t5I2HCzMrcHxE270=,iv:eaKbNgzYOcSzLR4FdjNfoAFw/XzeZLw2G4aTxJmvxRQ=,tag:Tp8Dh8b+oHzhCcZeD+4XYw==,type:str]
    db-init-sql: ENC[AES256_GCM,data:Ya8QgdYAKKkJ9JiW8R23lGlwstUcPh7UKRYEIIsw6ZeMy1aMeD99sYsE6uEc3KtINUYSYUa/Yy5hJBOEO9ATkL/+yIg4HSj/9aPDzNzea98o48Jw8Rfa3jEnGtzEIiAlnkWV7++v0PPaaxeO0s1Vtb+BYEzbHjGakAhCa00/cRCGwZp9PKz4LjOXYELZ5JCpZTCfooDw/HmWGC8TtYu6l2KPhSE0815RjE8TLnXR8uUc,iv:2QRoQqr1N0g1KKRXMBMmElLH0hPorkFvm3VkXhzRKi0=,tag:tDG8CHAIE0t0ZhHiA4r27A==,type:str]
sops:
    age:
        - recipient: age13ttsf4ee2xr4e90ydsrj9hk2gpjk9hktmxam0r08zeny75dwlc7qxap6zk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoVllkaHJ3RDRiNm0yN3NN
            T2RJRThNRGpaOUdwa2ZvWVRoQkY0VXZlZEN3CnJUWENQdXNMNXpseWdnSHI2bENH
            SVdLT3pqL2VZSmVwTlNqUHlZYlVjWEEKLS0tIGF1cGlpcEVHL1F5MTg5MEhQMWZt
            OEx4ZzErZm8xUDRoeERxSEJ3TzZ3Mk0KmiuF9ePFUTvxDLT8Yi6Pelb8vQB008Tu
            FklyJ6AQDjo5+WmTrn/YkAmJUWfql9BpHYAbP5ZzXHExeH7Z17hbWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-31T15:17:13Z"
    mac: ENC[AES256_GCM,data:lx8J5PIhC+b640A6wLQ1VRPqcoKprI4vN9iquD+ner3hdtWbcTEgtpAbAFhsQbTjx75BAwPdxr8eHHo5VNLnj2Iy6Yk236sl6tsKJYwg+pdiXi42ZK2jK6XYWCRiw/rElcsCTn74TXun73fwamLDXKL/+K6VeCFvUt1bT5dXvB4=,iv:57Se03PV77J6HEW0cZlpLwKCv1Dr9R9IUmoKIOkffNo=,tag:gcmFdwOn/el06YtsEEVhZA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
