apiVersion: v1
kind: Secret
metadata:
    name: keycloak-admin-secret
stringData:
    admin-password: ENC[AES256_GCM,data:RpO24nJ/tzQetQ==,iv:8TFspkldD6zKUn7JhiaITtcSFcTrMg4atC4z194lYAs=,tag:5++s+tZMqoj9s7mRe1/Mbw==,type:str]
sops:
    age:
        - recipient: age13ttsf4ee2xr4e90ydsrj9hk2gpjk9hktmxam0r08zeny75dwlc7qxap6zk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoVllkaHJ3RDRiNm0yN3NN
            T2RJRThNRGpaOUdwa2ZvWVRoQkY0VXZlZEN3CnJUWENQdXNMNXpseWdnSHI2bENH
            SVdLT3pqL2VZSmVwTlNqUHlZYlVjWEEKLS0tIGF1cGlpcEVHL1F5MTg5MEhQMWZt
            OEx4ZzErZm8xUDRoeERxSEJ3TzZ3Mk0KmiuF9ePFUTvxDLT8Yi6Pelb8vQB008Tu
            FklyJ6AQDjo5+WmTrn/YkAmJUWfql9BpHYAbP5ZzXHExeH7Z17hbWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-17T02:09:54Z"
    mac: ENC[AES256_GCM,data:aJhzthe7XMgjEEMLPCW+BNtGvPf5+Un2ByQPx9pN26TwKfeuLoXF5xyCusOb+0JLXfo9Cuy7Hn0CKw32h1PWBgXuKQDNcRZCruOC64KrOkaqCTJB3OoJ2GBKNfT5goGYvlZnlbyJBRMVfliz+KXB5K1BiSpfjfAl5UycnhLm0B4=,iv:mUWNEoY0xg74kECY+ipVkFHDjsCaearcYXguJii4rfQ=,tag:Kd+YWC+jn+4RIbYU5tAnrg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
