---
apiVersion: v1
kind: Secret
metadata:
    name: keycloak-admin-secret
stringData:
    admin-password: ENC[AES256_GCM,data:RpO24nJ/tzQetQ==,iv:8TFspkldD6zKUn7JhiaITtcSFcTrMg4atC4z194lYAs=,tag:5++s+tZMqoj9s7mRe1/Mbw==,type:str]
sops:
    age:
        - recipient: age13ttsf4ee2xr4e90ydsrj9hk2gpjk9hktmxam0r08zeny75dwlc7qxap6zk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoVllkaHJ3RDRiNm0yN3NN
            T2RJRThNRGpaOUdwa2ZvWVRoQkY0VXZlZEN3CnJUWENQdXNMNXpseWdnSHI2bENH
            SVdLT3pqL2VZSmVwTlNqUHlZYlVjWEEKLS0tIGF1cGlpcEVHL1F5MTg5MEhQMWZt
            OEx4ZzErZm8xUDRoeERxSEJ3TzZ3Mk0KmiuF9ePFUTvxDLT8Yi6Pelb8vQB008Tu
            FklyJ6AQDjo5+WmTrn/YkAmJUWfql9BpHYAbP5ZzXHExeH7Z17hbWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T17:00:33Z"
    mac: ENC[AES256_GCM,data:RhoSkREtaivc0DYZIXzDjNbvSQ0ehU4YGLgouLDgqknk1HwVBzYkb5rElFodvIto53I1v/VuDdCG+ui9/mwBLCDeGiYJAMBrHQ0nzIDV0peyvyN/UO97pMOzNhu97fG7YqZDWhc8UgZ3MqCmDqlIyyNH38/hFcTSYsSUCPjWTn4=,iv:Wq7axcwphjMCk+rboRMwvHbr+P2bmp9soSuqOED6BdU=,tag:j4ov1Y7YKcGmPVg2WOB6RQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: keycloak-db-secret
stringData:
    db-username: ENC[AES256_GCM,data:xMbdAbJd9HQ=,iv:zWkpqY2gHdVwzW3dxO91Amc5HRDExOsrxhvEWJFNuNM=,tag:Z8X7mUQv2fLKxP6F+yXUaA==,type:str]
    db-password: ENC[AES256_GCM,data:keUrnfeVckhf4WlJfzdOAw==,iv:5Jgj1kimqhWlapJCpnC9PXVOqCb2PaJwD5Zt3zUqFiM=,tag:6DPMCvRD5Z1pYH9gBRWFKg==,type:str]
sops:
    age:
        - recipient: age13ttsf4ee2xr4e90ydsrj9hk2gpjk9hktmxam0r08zeny75dwlc7qxap6zk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoVllkaHJ3RDRiNm0yN3NN
            T2RJRThNRGpaOUdwa2ZvWVRoQkY0VXZlZEN3CnJUWENQdXNMNXpseWdnSHI2bENH
            SVdLT3pqL2VZSmVwTlNqUHlZYlVjWEEKLS0tIGF1cGlpcEVHL1F5MTg5MEhQMWZt
            OEx4ZzErZm8xUDRoeERxSEJ3TzZ3Mk0KmiuF9ePFUTvxDLT8Yi6Pelb8vQB008Tu
            FklyJ6AQDjo5+WmTrn/YkAmJUWfql9BpHYAbP5ZzXHExeH7Z17hbWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T17:00:33Z"
    mac: ENC[AES256_GCM,data:RhoSkREtaivc0DYZIXzDjNbvSQ0ehU4YGLgouLDgqknk1HwVBzYkb5rElFodvIto53I1v/VuDdCG+ui9/mwBLCDeGiYJAMBrHQ0nzIDV0peyvyN/UO97pMOzNhu97fG7YqZDWhc8UgZ3MqCmDqlIyyNH38/hFcTSYsSUCPjWTn4=,iv:Wq7axcwphjMCk+rboRMwvHbr+P2bmp9soSuqOED6BdU=,tag:j4ov1Y7YKcGmPVg2WOB6RQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
