apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cert-manager-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword

  target:
    name: cert-manager-secret

  data:
    - secretKey: api-token
      remoteRef:
        key: cert-manager-secret/api-token
