apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:dA5xiPNx7Fr7hm7X8pNkptBpvACaRbGf+Wwc9Cux804TEFzdJ/yzwg==,iv:/8wrC5safnMAT4PkBzJAWvwd+GlzSaEH1aWhwLU605Q=,tag:1GqEx0NOYkAwq5/cOOqRtA==,type:str]
sops:
  age:
    - recipient: age13ttsf4ee2xr4e90ydsrj9hk2gpjk9hktmxam0r08zeny75dwlc7qxap6zk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJeVFOaXUyK25tQW1Gb3Jv
        TmNiWVBveTFkNk9wSWd2S3NOdXZmN3d5cVRBCmtiT2pSdDZWUlcwK3d6cGs5Q0lJ
        S1hvSklFUXFaeEg1c3o4YW5UUXdKL0kKLS0tIGNrMFk4ZjB5enFYU1dmdzA0TUMr
        MG02ZVVPTWVYakkwWG9KZHJIdTNWOFUKuHpauY45jwi88HvfRIXGCOupPpvCPo+g
        0OkT+ePsG4Q30NkXdjJgbjPQ6o3yL3NNi7NLnOXsxKW7U3+jYqey2A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-06T22:47:37Z"
  mac: ENC[AES256_GCM,data:A7nTwpNhc6XbO8XiBzadSl8uCsdqBJhd+QInYTs3pn2/NPgJdRZWj3hIroZ9/uXmTydKpCb8upTCmpFk3dn1vlG9yNHw52igQc0TE1uZk097xnGL90IhifHLLoIpHlva/BBGIIv1q2Yh1KnAQfSHuV8AALXRQBWcCRVRwnZmr30=,iv:DUd4I2AHq6Cu/Egj/rmYhXRNoNlEPRuQtNxr2x1ONjs=,tag:dVgCQGfV+FDPzriXPqh9zw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
