apiVersion: v1
kind: Secret
metadata:
    name: forgejo-renovate-secrets
stringData:
    RENOVATE_GITHUB_COM_TOKEN: ENC[AES256_GCM,data:d6Rr8L+wk4IKPEdO72Z3GQhdwkHaUQdNFg2z5t4aQdm3bwk82mefGA==,iv:7CGtCypXQGNudyyMyVyql5MDiab/568VnL8l7uwXuLU=,tag:vHJTyjRUCj4C7CrqoaGuEA==,type:str]
    RENOVATE_TOKEN: ENC[AES256_GCM,data:T8X9zIlZDoKOW4b1l1Fc1uJittQCjfrXIeIK1hhky2AjalkJU+5Fug==,iv:bNf+MWkih6xVwbCPrIBJcJ6oB5F0PylCiNiLo3gGUqg=,tag:ShgJMbtJwPKd9GMhCzl12A==,type:str]
    RENOVATE_GIT_PRIVATE_KEY: ENC[AES256_GCM,data:2FOvDqv/uOmwrPPtc9Q2Zk9zGMsxVwO+QuelrLDHuuvCeLOZurZv8dDsOnXhQExB2WP+sdqKAsLSSBKEsiR0p6Zb9rlABUXiAbFwXlvTYJcdD+cKTsM4u7JstV55bquTGf3AyATaPkZmUoGRYWEnvKc/IZQaO+m1dI8EeP9SVyaj7da0VWFsFiKGLpGHWbBCfM+pE/HQ2CdhkZKyCch3TV997NeLIYSR5WjNjRQ1+btJxlW3gpmgSbmC9wvji949m76OfH1jOpsGwQe9XOklEtLebe6lwuigByW8/5kPG9SmQJJ2+A+SPeAxt7MzCS7SJpuVUOppiljP/Yw1mk7Qon3k5ID3eIFM98LT2oMOZIfXK83OUq+P8g2wmBx9yRTw0m20ivQMvK7Mwolt141ExQaErUse1hIf+4/XAAFB44wHgYi81fc718LCpn9qDh89gY0mJQWT7BfUGw9QKNaQa0P7g98OJmDJXU7zSU+KB93/vKBFai/VOrhM9veGoM/MpiCj3qv/dFG2k7VNjfg3,iv:g2aEtw9bTOOyrZ6wRvk/1eiqi/vy5DOpAQsljE9i/Hc=,tag:SOS6+QumWjViIjPpxSNbzA==,type:str]
sops:
    age:
        - recipient: age13ttsf4ee2xr4e90ydsrj9hk2gpjk9hktmxam0r08zeny75dwlc7qxap6zk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVOU1ERVBvUjRyTnRhYXZh
            dEQ0cEZjeU1mOCtUaldnRWRibDJ5MGVKREFFCkV4U3NYR2s0eDN6T1RZS0Z0M0hz
            TUFsTTVYcFA2c1VkY0ZtUEVUN3cyTUkKLS0tIFluMG9NZjJwS1RFcUZUWlZVcGF5
            Wjl4dkFWQnV6cGVac0oyT2lYK0pFME0Ka/8Qg/hw6FhUPg/horqu9P5o9dxcnM5m
            IyZ8VPBWljWotZm9EPA6q9bZTO3G7933aogwYz3C1C5G7rk/DywG+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-06T23:47:43Z"
    mac: ENC[AES256_GCM,data:VWrnrCKye/ov/LpSQuQ56oVQ/iabeoVvNc659IhqLLe8J/0GUKXdKLZ5FIBR6bM1iy8G4QzOoU16kAWDfyObb/41DXPmjcLw+wzXRgTQ6/e42kusiAKFv+roJD0vRZB5nzhQeqGTZCA84cot689RdBnQlyH2zkDZBLnJbWmOfFU=,iv:M/ht4SeEXOAu852gExlS8MtncNIxxK99Kau4TbWUP3Y=,tag:xjP+jISTJp0brtc2kV804Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
