---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: automation

components:
  - ../../components/sops
  - ../../components/repos/app-template

resources:
  - ./namespace.yaml
  - ./busabase/ks.yaml
  - ./n8n/ks.yaml
