apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-db-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical

  target:
    name: paperless-db-secrets

  data:
    - secretKey: PAPERLESS_DBPASS
      remoteRef:
        key: /databases/PAPERLESS_DATABASE_PASSWORD
    - secretKey: PAPERLESS_DBUSER
      remoteRef:
        key: /databases/PAPERLESS_DATABASE_USERNAME