apiVersion: v1
kind: Secret
metadata:
    name: paperless-secrets
stringData:
    PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:793x9Is=,iv:2aMEUQpG0inntt1GRIHsf/H7cLmgIoO7NLhy84d9kXI=,tag:Q92at45+DfMe3Zt3rEDYOA==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:BkhVXD+pLctu1g==,iv:weXbNgUGIHq1Vrahr/Yb0ks2Eo3Yer77PtypTDMMWxE=,tag:/rYn3SJdhKV/QifNtgfoZw==,type:str]
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:AfgbSxysQVwFxH+OX2s2Xnib7PJOrPnaXL+LQ2lpbGrSDlzLAtgDSWi+ZiA=,iv:mZqJBO6pydq7sw6HPJstY9gNOJXonnrwDeHPiYTviI8=,tag:QamDvtcsjMnSZeFSVPjbQQ==,type:str]
    PAPERLESS_SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:OxPFx9YHqxcexgm0btVBew/7rPeQJ7HUdPAkZtPtash4z4PG+MOWeJJ2i9a5WzjVLjbolg4qouKScwlNWoyjjaDt1Wn7/G3iP/YX1O3yIZmO/3gKNspyb4++WPpXrSGuWhJX+g1ECgyFkmJDYIs4WEq2VhD+BJpi93IO61r+fUouZdcVCekLRnIduzjSkhIR/1FUQG9IZWaBvA5oulyrr2rcZFL4vWGa21uXEUaDpZSC20mFyrsPzZSl4vK2RRmLGZQWP6X4aGRpvQsZwGp9KgNtL77EAqsXny8I17k91KUzqejMCSra2pAl11d2i/gK3vZCy2QeeH32zJkevZ9AjQq71f8HNuqE4AxcM9tTqeTa1Sqj8Dv2wi8W1FiyMcwmT8ThVDCGSkDQQFZI1TR8qqDqq6DeAecnWzKRI+DCyRyAnM4dAdark0Is/FyJZdTlU/Z6GksKP4bozu0UwPu9IpjALP0T4XKb1jvkhpPTAjPwX9+60i9LKhr/GTI+CJiJ6aqCpN3MeQz3NU1eaSda3+0ZkjmNJFWJLjCSHSkWIgU=,iv:5pilF9PEOkEdRliIeuHxd1SKfdWCoe1mkh7D0foPWX4=,tag:GZPDN4KoId20mgeXHVr1bw==,type:str]
    PAPERLESS_DBSSLMODE: ENC[AES256_GCM,data:+4eVxtHoPQ==,iv:V8/B9ko+rrRyF9aCIJwhMKvzjUiGuUdFs7lxSVY5ZWA=,tag:kEIz3nMJOQLUmd9drRUVmw==,type:str]
sops:
    age:
        - recipient: age13ttsf4ee2xr4e90ydsrj9hk2gpjk9hktmxam0r08zeny75dwlc7qxap6zk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzZU1hZWprQ2NjVkR1UXhZ
            ejFhYzBXQXMxSWtFM0kwOUxoWkVqOE9ZWVUwCmxBV1I4VTcyMlpvajl5K0lnei9m
            d21TdHVQL2RrOXRZNXpOTVZWT2RsaGsKLS0tIG41OVpwUXhsQnBsUkFYZVhtamli
            dll2Yk5Nck56Q2JSWG9vMW9Pa3VmN2cKD3oMXHUOWNkZg7ekWHAXD4d9PfkpGRnv
            ylbMJF4Ilywx5YKyv8520k5RciDxVksvNsnLO7c7LEV2Y1Y2YrPchQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-20T04:43:13Z"
    mac: ENC[AES256_GCM,data:Ga2h9Yj+5KuGK4zUocsOKEYNSRoyxR4WhWFElWah1eDS11v4L2/3rWXbjuC1Va1t95zYYXFHxkjyPB34sMlqRQXgDvCmJy6aLC5QxxJmUGvD0wlFA7lWxTgtm5Zq8MhP8odO/f1Iz1i9BYqCXcRKPBylTwal9Aa8T5IWll5B9PM=,iv:FuzSTmkoDc+v8JOZVuF2WFHEwrn0Z8D8FTzylxx4Ocw=,tag:l+MHOB58L4BIIFH/2SUzsg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
