apiVersion: v1
kind: Secret
metadata:
    name: paperless-secrets
stringData:
    PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:793x9Is=,iv:2aMEUQpG0inntt1GRIHsf/H7cLmgIoO7NLhy84d9kXI=,tag:Q92at45+DfMe3Zt3rEDYOA==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:BkhVXD+pLctu1g==,iv:weXbNgUGIHq1Vrahr/Yb0ks2Eo3Yer77PtypTDMMWxE=,tag:/rYn3SJdhKV/QifNtgfoZw==,type:str]
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:AfgbSxysQVwFxH+OX2s2Xnib7PJOrPnaXL+LQ2lpbGrSDlzLAtgDSWi+ZiA=,iv:mZqJBO6pydq7sw6HPJstY9gNOJXonnrwDeHPiYTviI8=,tag:QamDvtcsjMnSZeFSVPjbQQ==,type:str]
    PAPERLESS_SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:WGwKLdFL28RtKzjxIuqQFzrWkVwtI9wiH/LpiSkjCPSWPVXFBHtFA682WWX9OvTo6U2VgOCPMfADibF5mnzV+oeVURPYBADtBPy1ydxuOforH/b9JxOsYSN26b5yT3r1WfF21x8fFepnBNxOkHVaDx8f41QtYrsaVOujfD3iKEkdbcbKNjX7VwZio+xJYlWExYR1vxc0yk+RH5diOCBLSzLx1YPB1HqcjkpuLgFAf9euD8A/poZXp+X/vUmrYsoL3EQIwRTsn22gD2WMTOBoKNqmGPhYERDEThnK/BaiXJxdJ8nVVHSAW0HVcvFgsNg6709JcwAVY6rGnQVQJDHrsogY9EcYUt+/dp48ruRgDXy0hdZkvQYwvWiylUonVqR34ukv/+TVl3DAiqy3QeBzzaeHFbw64GM6hJmy06EgoFJSNQbHkiwZEwrXXWowk5YN3rbNaaEzSanocspSszsF4/wtqiJAAmtnKmIhEINXCFGyusUIY8ShXvLapWQqWVHwrOBxyMjA7Snla6SC9o4ndB/3vz9A64O8NFb3LPkQ,iv:oTm6taeB/CWDtt70xr1zl0iyQylAyeKzsVzCQyNaMBI=,tag:fT7pvJbHdmzuho31ZpMPRA==,type:str]
    PAPERLESS_DBSSLMODE: ENC[AES256_GCM,data:+4eVxtHoPQ==,iv:V8/B9ko+rrRyF9aCIJwhMKvzjUiGuUdFs7lxSVY5ZWA=,tag:kEIz3nMJOQLUmd9drRUVmw==,type:str]
sops:
    age:
        - recipient: age13ttsf4ee2xr4e90ydsrj9hk2gpjk9hktmxam0r08zeny75dwlc7qxap6zk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzZU1hZWprQ2NjVkR1UXhZ
            ejFhYzBXQXMxSWtFM0kwOUxoWkVqOE9ZWVUwCmxBV1I4VTcyMlpvajl5K0lnei9m
            d21TdHVQL2RrOXRZNXpOTVZWT2RsaGsKLS0tIG41OVpwUXhsQnBsUkFYZVhtamli
            dll2Yk5Nck56Q2JSWG9vMW9Pa3VmN2cKD3oMXHUOWNkZg7ekWHAXD4d9PfkpGRnv
            ylbMJF4Ilywx5YKyv8520k5RciDxVksvNsnLO7c7LEV2Y1Y2YrPchQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-20T05:03:11Z"
    mac: ENC[AES256_GCM,data:bSprTTewOUNntHAfUBeX3gDpIypytrIyfZ25qhJxRnVqE8rkbx+MY0uS4YY6mXGB8rEEeTzBD+XmXeuN8sikrt8RTfGhxmaPqN4y/PC5OzssGphdDuvNxTLWEwDNjXH3vu7+k/QCzk7paROz8aJhR6XoOfouTUuRStuqPWTJCEU=,iv:gvAo2AotHWvzo8TKmIlsybsXm+OKop/Huz/1NR9c3Hw=,tag:nEDSvxrAyrKtIYQmK8xTRA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
