apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-database-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical

  target:
    name: immich-database-secret

  data:
    - secretKey: db-password
      remoteRef:
        key: /databases/IMMICH_DATABASE_PASSWORD
    - secretKey: db-username
      remoteRef:
        key: /databases/IMMICH_DATABASE_USERNAME