apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-nfs-pv
  namespace: default
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-immich
  nfs:
    path: "/mnt/Storage/Files/k8s/apps/default/immich"
    server: ${NFS_HOST}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-nfs-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-immich
  resources:
    requests:
      storage: 1Ti