apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: crowci-forgejo-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword

  target:
    name: crowci-forgejo-secrets

  data:
    - secretKey: CROW_FORGE_LOCAL_CLIENT
      remoteRef:
        key: crowci-forgejo-secrets/CROW_FORGE_LOCAL_CLIENT
    - secretKey: CROW_FORGE_LOCAL_SECRET
      remoteRef:
        key: crowci-forgejo-secrets/CROW_FORGE_LOCAL_SECRET
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: crowci-default-agent-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword

  target:
    name: crowci-default-agent-secret

  data:
    - secretKey: CROW_AGENT_SECRET
      remoteRef:
        key: crowci-default-agent-secret/CROW_AGENT_SECRET
