---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: crowci
spec:
  chartRef:
    kind: OCIRepository
    name: crowci
  interval: 1h
  values:
    agent:
      env:
        CROW_BACKEND_K8S_STORAGE_CLASS: "ceph-filesystem"
        CROW_BACKEND_K8S_VOLUME_SIZE: "1Gi"
        
    server:
      env:
        CROW_ADMIN: "rbihun"
        CROW_HOST: "https://build.${SECRET_DOMAIN}"
        CROW_OPEN: "true"

        CROW_FORGES: "local"
        CROW_FORGE_LOCAL_TYPE: "forgejo"
        CROW_FORGE_LOCAL_ICON: "forgejo"
        CROW_FORGE_LOCAL_URL: "https://code.${SECRET_DOMAIN}"

        CROW_PLUGINS_PRIVILEGED: "codefloe.com/crow-plugins/docker-buildx"

      extraSecretNamesForEnvFrom:
        - crowci-forgejo-secrets

      metrics:
        enabled: true

    prometheus:
      podmonitor:
        enabled: true
        interval: 60s
    grafana:
      dashboards:
        enabled: true