apiVersion: v1
kind: Secret
metadata:
    name: crowci-forgejo-secrets
stringData:
    CROW_FORGE_LOCAL_CLIENT: ENC[AES256_GCM,data:zeMzZBqyClx2DL3+SSc3/IwprEbqMURI0SJTNgGjyTKd0/T0,iv:nVYaCVYuT2bDKFDWMvBG2FTL26jqDUNzxT9pShnYZ/s=,tag:mMddE+aRN8DHjltgKoe1NA==,type:str]
    CROW_FORGE_LOCAL_SECRET: ENC[AES256_GCM,data:wdAdgjlpnlbzq3B5noq6LRbs+HxA3uwpvBhzPgOcdEO5qsPsOJWjtqlcsiqGDGFg7Z2Tiqe19yg=,iv:ov5ZPH1FuUJa+5eUfh/eV9IAgE6DGfKQrIXEx37q/0I=,tag:+pXpBVrGD3gJL/TMDUIXwg==,type:str]
sops:
    age:
        - recipient: age13ttsf4ee2xr4e90ydsrj9hk2gpjk9hktmxam0r08zeny75dwlc7qxap6zk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZQnFtUUFSdnV4Y1BwTVpU
            K3VkbFZ0N2VPeTBMS1MxTHJuTkNpZ1JWZDBnCnBoNnhIUE5HVzV6VjZaVGgrc1Js
            bERNRktJMk5QTXFzTXJqSk95ejlVcDAKLS0tIEd6YUdIdW9PYnRLNi9MOGtrK05C
            SjlnamFMWklubnZ3OEE0bEk5NmJYREUKImO0/O9/un3CGF29RgcNXOf5ET2bGa6+
            5ExaENOmGQoyXXRaJxAz+kjzSGlbNW2YVb7sWPd9pT293p1kS80MTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-14T20:59:28Z"
    mac: ENC[AES256_GCM,data:1UuvSYwiEwjU068M+umVwkUmg+gOdRUjcWqToKvUX2jXVXTQ3Zhc5+Wi/FZ7aliexm/XE8oqztWa70zGW3a25cG1WN8vvKia+m+tALIgW4puM+xhlGy55YiF52oFJXNcf8n9zUGm8TnxznBfzUmNauwI7c9qwd3cOwggxRGvrqQ=,iv:jZe/jP4oP1V+euXhpW518jfpdahUhKLc58ZRr6TXFak=,tag:T721OAe4HnfENbDBbea4zQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: crowci-default-agent-secret
stringData:
    CROW_AGENT_SECRET: ENC[AES256_GCM,data:K6HgS6VpBXV6ZBfU+xUrhyVsxsWhjSB5cnwvkXbewZ7bfwmd+jeHOxKi5zhSCIMCI1GcgoH5bDAtVIKGDCFl,iv:wauhYodGL13V1kEUZYdW4y9+gReheWk5hOcIAHRltls=,tag:0V8JlBnRG4i/Lrh36p+RTQ==,type:str]
sops:
    age:
        - recipient: age13ttsf4ee2xr4e90ydsrj9hk2gpjk9hktmxam0r08zeny75dwlc7qxap6zk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZQnFtUUFSdnV4Y1BwTVpU
            K3VkbFZ0N2VPeTBMS1MxTHJuTkNpZ1JWZDBnCnBoNnhIUE5HVzV6VjZaVGgrc1Js
            bERNRktJMk5QTXFzTXJqSk95ejlVcDAKLS0tIEd6YUdIdW9PYnRLNi9MOGtrK05C
            SjlnamFMWklubnZ3OEE0bEk5NmJYREUKImO0/O9/un3CGF29RgcNXOf5ET2bGa6+
            5ExaENOmGQoyXXRaJxAz+kjzSGlbNW2YVb7sWPd9pT293p1kS80MTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-14T20:59:28Z"
    mac: ENC[AES256_GCM,data:1UuvSYwiEwjU068M+umVwkUmg+gOdRUjcWqToKvUX2jXVXTQ3Zhc5+Wi/FZ7aliexm/XE8oqztWa70zGW3a25cG1WN8vvKia+m+tALIgW4puM+xhlGy55YiF52oFJXNcf8n9zUGm8TnxznBfzUmNauwI7c9qwd3cOwggxRGvrqQ=,iv:jZe/jP4oP1V+euXhpW518jfpdahUhKLc58ZRr6TXFak=,tag:T721OAe4HnfENbDBbea4zQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.1
