apiVersion: v1
kind: Secret
metadata:
    name: crowci-forgejo-secrets
stringData:
    CROW_FORGE_LOCAL_CLIENT: ENC[AES256_GCM,data:E7cnsRcT8vQLrvTfDFqpEKLA+8GGw1NX078pMAgSuECyLxVz,iv:7qZRZCm4sammoaH4+lmUdwJEBG8fd9tTVrmNKVwlOkk=,tag:OgwwNE4LGK4YI/ypAC/tmQ==,type:str]
    CROW_FORGE_LOCAL_SECRET: ENC[AES256_GCM,data:DqFQ0N62NPt/Vec69nvbi7kxlgU/utblhmZl0dkja3mfQP68ouSCG4/FTTvt8RccvXyMEOmGra0=,iv:N3yqniAWLC9+hPKjQpVLz4hMf1wX6rTmw2ndqQ5Aydo=,tag:zLZvmhn/hX3bwwpbCAbuKQ==,type:str]
sops:
    age:
        - recipient: age13ttsf4ee2xr4e90ydsrj9hk2gpjk9hktmxam0r08zeny75dwlc7qxap6zk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZQnFtUUFSdnV4Y1BwTVpU
            K3VkbFZ0N2VPeTBMS1MxTHJuTkNpZ1JWZDBnCnBoNnhIUE5HVzV6VjZaVGgrc1Js
            bERNRktJMk5QTXFzTXJqSk95ejlVcDAKLS0tIEd6YUdIdW9PYnRLNi9MOGtrK05C
            SjlnamFMWklubnZ3OEE0bEk5NmJYREUKImO0/O9/un3CGF29RgcNXOf5ET2bGa6+
            5ExaENOmGQoyXXRaJxAz+kjzSGlbNW2YVb7sWPd9pT293p1kS80MTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-07T00:12:32Z"
    mac: ENC[AES256_GCM,data:V0677PzyhsyH8VICXjRuMxRlSw9tBiwbxnn+Si8XEcFCDKQVK9MxtX2tOKe8FLWyKesrz7PtDR8CrYxa2RsR5b/GcC81kPvbSOO0vlHASpOJUoSqAndYWsbiUsQe+7Sjf9r/58+fxkNc9a6orLfyFA/gb+pGryYePzI25TS+oTo=,iv:4Q0dhIEnhu/xkfVDOnwyAgi5rVwlwB6Cu/FeJFUR9yg=,tag:Nhtnvr6/mYlaHDI6y4hqvg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: crowci-default-agent-secret
stringData:
    CROW_AGENT_SECRET: ENC[AES256_GCM,data:tgLM5Cvw8svGcZUf6GsPxZW/kD5rH76w4jvxzTDw2Kf7NSfBNRu0KRxN+OBochf02qTd1xQGcXAXRRFZD5g2Cg==,iv:I5e2uGdJjy9MSlLoLFg/uwkuU4M3THryT3ujrsH142A=,tag:nx2UrFNqxOJaDPQPWLkGEw==,type:str]
sops:
    age:
        - recipient: age13ttsf4ee2xr4e90ydsrj9hk2gpjk9hktmxam0r08zeny75dwlc7qxap6zk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZQnFtUUFSdnV4Y1BwTVpU
            K3VkbFZ0N2VPeTBMS1MxTHJuTkNpZ1JWZDBnCnBoNnhIUE5HVzV6VjZaVGgrc1Js
            bERNRktJMk5QTXFzTXJqSk95ejlVcDAKLS0tIEd6YUdIdW9PYnRLNi9MOGtrK05C
            SjlnamFMWklubnZ3OEE0bEk5NmJYREUKImO0/O9/un3CGF29RgcNXOf5ET2bGa6+
            5ExaENOmGQoyXXRaJxAz+kjzSGlbNW2YVb7sWPd9pT293p1kS80MTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-07T00:12:32Z"
    mac: ENC[AES256_GCM,data:V0677PzyhsyH8VICXjRuMxRlSw9tBiwbxnn+Si8XEcFCDKQVK9MxtX2tOKe8FLWyKesrz7PtDR8CrYxa2RsR5b/GcC81kPvbSOO0vlHASpOJUoSqAndYWsbiUsQe+7Sjf9r/58+fxkNc9a6orLfyFA/gb+pGryYePzI25TS+oTo=,iv:4Q0dhIEnhu/xkfVDOnwyAgi5rVwlwB6Cu/FeJFUR9yg=,tag:Nhtnvr6/mYlaHDI6y4hqvg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
