---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pocket-id-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword

  target:
    name: pocket-id-secret
    template:
      type: Opaque

  data:
    # openssl rand -base64 32
    - secretKey: ENCRYPTION_KEY
      remoteRef:
        key: pocket-id-secret/encryption-key
