---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: router-internal
spec:
  parentRefs:
    - name: envoy-internal
      namespace: network
      sectionName: https
  hostnames:
    - llm.${SECRET_DOMAIN}
  rules:
    - backendRefs:
      - name: llmrouter-router-proxy
        port: 8080
