apiVersion: v1
kind: Secret
metadata:
  name: anthropic-credentials
stringData:
  ANTHROPIC_API_KEY: ENC[AES256_GCM,data:SdRQSQe6ipox36xIbwfYrCvSebYwD+nCt/BXt9o41Ny7osY6ovUpsezzbaL8yyDG2IvUQC9VWdT5i9WHTTwWM2Gb1msoPoQ5EF5RmNrx0zBLkevcJTRA3ZWV6EQQeZyqm+FEvXvlGaIH0AU9,iv:egUmGOJ0LykrGqim9C8H8xjz5JOFq2DkLwjgTkUOp9o=,tag:EjNQKSOEUHYx6psa8HFKLQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwMGlqTElxczV0bjVPQVVN
        K2dyeGVWQi9EZ0pmWGQvbVlqaFhvUEkzT0FVCnltczZncVU1M0psRy9CVnBvTHJj
        bHhWYjJtUmFsV3RCOEFMdXgxemcyZFkKLS0tIGxORmZhWE9CMTIwYnB1REtRU1NT
        U2RRTTBOa0Zyb29CZ0h1dDI1aUdNNmsKiq9wRhP+8CLO5qtL3/Sw0DzVq+OFWWrw
        lUKPb6CIGIqbs2b387ZStG9Slf2HzC0lIRPiUzsMeMFLD0D6qqfdyQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age13ttsf4ee2xr4e90ydsrj9hk2gpjk9hktmxam0r08zeny75dwlc7qxap6zk
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-05T23:41:16Z"
  mac: ENC[AES256_GCM,data:+qGFkQabfNQMtYEpM6aGP4tvVSIt2IHobXcnDi73qk38aPIMa5eVPtQrZpVZV8wgAoQa+kjVV4fsxeBP2/nn+PwJINv5Uy6ptLn7nwydt1QLKA7PGRnLkorRVPpFK/nod19ysUun1KBggRJHp0WFkR5uwHykwyIwSlN/Xlizd6E=,iv:6KkuK5/7m65o0u9/f/Z+lplWDhfHo0jfILOhPheqhRY=,tag:d4I/U/XXojKfZTlEEakCug==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
